Repository DouyinFE/semi-design, pull requests merged in 2021-12, with the labels that each got.

#386 fix(form): withField return component lossing ref when it without fil…
  packages/semi-ui/form/hoc/withField.tsx
  packages/semi-ui/radio/_story/radio.stories.js
Labels: bug

#411 Fix scss charset warning in vite
  packages/semi-scss-compile/src/bin.ts
  packages/semi-scss-compile/src/index.ts
  packages/semi-scss-compile/src/utils/compiler.ts
  packages/semi-scss-compile/src/utils/generateSCSSMap.ts
  packages/semi-scss-compile/src/utils/writeFile.ts
Labels: build

#407 fix: [Description] When the description type is plain, the key is nod…
  packages/semi-ui/descriptions/__test__/descriptions.test.js
  packages/semi-ui/descriptions/_story/descriptions.stories.js
  packages/semi-ui/descriptions/item.tsx
Labels: bug

#413 feat(a11y): switch aria #205
  content/input/switch/index-en-US.md
  content/input/switch/index.md
  packages/semi-ui/spin/icon.tsx
  packages/semi-ui/switch/_story/switch.stories.js
  packages/semi-ui/switch/_story/switch.stories.tsx
  packages/semi-ui/switch/index.tsx
Labels: enhancement, feature request

#414 feat(a11y): progress aria #205
  content/feedback/progress/index-en-US.md
  content/feedback/progress/index.md
  packages/semi-ui/progress/_story/progress.stories.js
  packages/semi-ui/progress/index.tsx
Labels: enhancement, feature request

#405 feat: [Cascader] support leafOnly #256
  content/input/cascader/index-en-US.md
  content/input/cascader/index.md
  packages/semi-foundation/cascader/constants.ts
  packages/semi-foundation/cascader/foundation.ts
  packages/semi-foundation/cascader/util.ts
  packages/semi-foundation/tree/treeUtil.ts
  packages/semi-ui/cascader/__test__/cascader.test.js
  packages/semi-ui/cascader/_story/cascader.stories.js
  packages/semi-ui/cascader/index.tsx
Labels: feature request

#428 fix: [Pagination] hideOnSinglePage take effect that make page size ch…
  content/navigation/pagination/index-en-US.md
  content/navigation/pagination/index.md
  packages/semi-ui/pagination/_story/pagination.stories.js
  packages/semi-ui/pagination/index.tsx
Labels: bug

#409 feat: [Cascader] support separator #408
  content/input/cascader/index-en-US.md
  content/input/cascader/index.md
  packages/semi-foundation/cascader/foundation.ts
  packages/semi-ui/cascader/__test__/cascader.test.js
  packages/semi-ui/cascader/index.tsx
  packages/semi-ui/cascader/item.tsx
Labels: feature request

#412 feat: [select] support inputProps
  content/input/select/index-en-US.md
  content/input/select/index.md
  packages/semi-ui/_utils/index.ts
  packages/semi-ui/select/_story/select.stories.js
  packages/semi-ui/select/index.tsx
Labels: feature request

#443 fix(datepicker): input year invalid #422
  packages/semi-foundation/datePicker/_utils/parser.ts
  packages/semi-ui/datePicker/__test__/datePicker.test.js
  packages/semi-ui/datePicker/_story/datePicker.stories.js
Labels: bug

#461 style(table): head row paddingY update to 8px #460
  packages/semi-foundation/table/table.scss
Labels: bug

#448 fix(datepicker): dateRange triggerRender close panel bug #410
  packages/semi-foundation/datePicker/monthsGridFoundation.ts
  packages/semi-ui/datePicker/__test__/datePicker.test.js
  packages/semi-ui/datePicker/_story/datePicker.stories.js
  packages/semi-ui/datePicker/datePicker.tsx
  packages/semi-ui/datePicker/monthsGrid.tsx
Labels: bug

#432 fix(inputnumber): input value format bug #431
  packages/semi-foundation/inputNumber/foundation.ts
  packages/semi-ui/inputNumber/_story/inputNumber.stories.js
  packages/semi-ui/inputNumber/index.tsx
Labels: bug

#450 fix(datepicker): can not close panel when preset dates is null or und…
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-ui/datePicker/__test__/datePicker.test.js
  packages/semi-ui/datePicker/_story/datePicker.stories.js
Labels: bug
