Repository DouyinFE/semi-design, pull requests merged in 2021-11, with the labels that each got.

#160 fix(select): renderSelectedItems ts bug
  packages/semi-ui/select/_story/select.stories.tsx
  packages/semi-ui/select/index.tsx
Labels: bug

#167 docs(table): add zebra stripped demo
  content/show/table/index-en-US.md
  content/show/table/index.md
Labels: documentation

#173 fix(datepicker): type=month can not select some date in US timeZone
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-ui/datePicker/__test__/datePicker.test.js
  packages/semi-ui/datePicker/_story/datePicker.stories.tsx
Labels: bug

#156 fix(list): List ts definition bug
  packages/semi-ui/list/index.tsx
Labels: bug

#191 docs(table): update drag sorting demo
  content/show/table/index-en-US.md
  content/show/table/index.md
  packages/semi-ui/table/_story/DragableTable/index.jsx
  packages/semi-ui/table/_story/DragableTable/index.scss
Labels: documentation

#192 fix(tooltip): event callback was not remove correctly
  packages/semi-foundation/utils/Event.ts
Labels: bug

#152 Fix/scss compiler local scss support
  packages/semi-scss-compile/README.md
  packages/semi-scss-compile/index.ts
  packages/semi-scss-compile/package.json
  packages/semi-scss-compile/src/bin.ts
  packages/semi-scss-compile/src/index.ts
  packages/semi-scss-compile/src/utils/compiler.ts
  packages/semi-scss-compile/src/utils/generateSCSSMap.ts
  packages/semi-scss-compile/src/utils/writeFile.ts
  packages/semi-scss-compile/tsconfig.json
  packages/semi-ui/scripts/compileScss.js
Labels: feature request

#135 feat: change jumpTo & selectDate ja_JP text
  packages/semi-ui/locale/source/ja_JP.ts
Labels: enhancement

#214 fix: [TagInput] Input value will be cleared when separator is not array or string #182
  packages/semi-foundation/tagInput/utils/getSplitedArray.ts
  packages/semi-ui/tagInput/__test__/tagInput.test.js
  packages/semi-ui/tagInput/_story/tagInput.stories.js
  packages/semi-ui/tagInput/index.tsx
Labels: bug

#210 fix: [Tree/TreeSelect] remove the padding and margin of loading Spin #181
  packages/semi-foundation/tree/tree.scss
  packages/semi-foundation/tree/variables.scss
Labels: bug, Style

#225 fix: [Cascader] When multiple and onChangeWithObject, the defaultValue passed into object[] does not take effect#184
  packages/semi-ui/cascader/__test__/cascader.test.js
  packages/semi-ui/cascader/_story/cascader.stories.js
  packages/semi-ui/cascader/index.tsx
Labels: bug

#223 fix: [Cascader] Fix the option will be filtered when the single-select defaultValue is disabled option #183
  packages/semi-foundation/cascader/foundation.ts
  packages/semi-ui/cascader/__test__/cascader.test.js
  packages/semi-ui/cascader/_story/cascader.stories.js
Labels: bug

#222 feat: [Select] support scroll into view #169
  packages/semi-foundation/select/foundation.ts
  packages/semi-ui/select/_story/select.stories.js
  packages/semi-ui/select/index.tsx
Labels: feature request

#240 style(input): border hover color is not correct
  packages/semi-foundation/input/input.scss
  packages/semi-foundation/input/variables.scss
Labels: Style

#164 fix(table): remove measure scrollbar column and use overflow scroll t…
  content/show/table/index.md
  packages/semi-foundation/table/bodyFoundation.ts
  packages/semi-foundation/table/rtl.scss
  packages/semi-foundation/table/table.scss
  packages/semi-foundation/table/variables.scss
  packages/semi-ui/configProvider/_story/RTLDirection/RTLWrapper.tsx
  packages/semi-ui/table/Body/index.tsx
  packages/semi-ui/table/HeadTable.tsx
  packages/semi-ui/table/Table.tsx
  packages/semi-ui/table/_story/BetterScrollbar.tsx
  packages/semi-ui/table/_story/table.stories.tsx
Labels: bug

#270 feat: [TagInput] support onKeyDown #255
  content/input/taginput/index-en-US.md
  content/input/taginput/index.md
  packages/semi-foundation/tagInput/foundation.ts
  packages/semi-ui/tagInput/__test__/tagInput.test.js
  packages/semi-ui/tagInput/_story/tagInput.stories.js
  packages/semi-ui/tagInput/index.tsx
Labels: feature request

#266 chore: [TreeSelect] modify renderSelectedItem type #265
  packages/semi-foundation/treeSelect/foundation.ts
  packages/semi-ui/treeSelect/index.tsx
Labels: bug

#261 fix(table): add dataIndex warn if column with filters or sorter
  content/show/table/index-en-US.md
  content/show/table/index.md
  packages/semi-foundation/table/utils.ts
  packages/semi-ui/table/_story/WarnColumnWithoutDataIndex.tsx
  packages/semi-ui/table/_story/table.stories.js
  packages/semi-ui/table/_story/table.stories.tsx
Labels: enhancement

#275 fix(datepicker): compatiableParse function ts error close#274
  packages/semi-foundation/datePicker/foundation.ts
Labels: enhancement

#157 Remove duplicate icon
  packages/semi-icons/src/icons/IconColumusStroked.tsx
  packages/semi-icons/src/icons/index.ts
  packages/semi-icons/src/svgs/columus_stroked.svg
Labels: bug

#289 fix(table): Pagination rename to TablePagination
  packages/semi-ui/table/interface.ts
Labels: enhancement

#307 fix: [TreeSelect] fix the error of using searchPosition and leafOnly …
  packages/semi-foundation/tree/treeUtil.ts
  packages/semi-ui/treeSelect/__test__/treeMultiple.test.js
Labels: bug

#299 fix: [Cascader] add value of triggerRender when multiple selection #259
  content/input/cascader/index-en-US.md
  content/input/cascader/index.md
  packages/semi-foundation/cascader/foundation.ts
  packages/semi-ui/cascader/__test__/cascader.test.js
  packages/semi-ui/cascader/_story/CustomTrigger/index.jsx
  packages/semi-ui/cascader/index.tsx
Labels: bug

#310 fix: [select] fix scrollIntoView crash for virtualization Select #308
  packages/semi-foundation/select/foundation.ts
  packages/semi-ui/select/_story/select.stories.js
  packages/semi-ui/select/index.tsx
  packages/semi-ui/select/utils.tsx
Labels: bug, 🛠 Work In Progress

#313 docs(darkmode): add demo and Timeline content add color scss variable
  content/start/dark-mode/index-en-US.md
  content/start/dark-mode/index.md
  gatsby-node.js
  packages/semi-foundation/timeline/timeline.scss
  packages/semi-foundation/timeline/variables.scss
Labels: documentation

#315 docs(table): use function component and add some notice
  content/show/table/index-en-US.md
  content/show/table/index.md
  packages/semi-ui/table/_story/Demos/columnRender.jsx
  packages/semi-ui/table/_story/Demos/controlledPagination.jsx
  packages/semi-ui/table/_story/Demos/customFilter.jsx
  packages/semi-ui/table/_story/Demos/default.jsx
  packages/semi-ui/table/_story/Demos/dynamic.jsx
  packages/semi-ui/table/_story/Demos/expand.jsx
  packages/semi-ui/table/_story/Demos/filterAndSorter.jsx
  packages/semi-ui/table/_story/Demos/fixed.jsx
  packages/semi-ui/table/_story/Demos/fullRender.jsx
  packages/semi-ui/table/_story/Demos/group.jsx
  packages/semi-ui/table/_story/Demos/headerMerge.jsx
  packages/semi-ui/table/_story/Demos/headerMergeJSX.jsx
  packages/semi-ui/table/_story/Demos/infiniteScroll.jsx
  packages/semi-ui/table/_story/Demos/onRow.jsx
  packages/semi-ui/table/_story/Demos/pagination.jsx
  packages/semi-ui/table/_story/Demos/resizable copy.jsx
  packages/semi-ui/table/_story/Demos/resizable.jsx
  packages/semi-ui/table/_story/Demos/rowSelection.jsx
  packages/semi-ui/table/_story/Demos/sortTree.jsx
  packages/semi-ui/table/_story/Demos/sortable.jsx
  packages/semi-ui/table/_story/Demos/span.jsx
  packages/semi-ui/table/_story/Demos/tree.jsx
  packages/semi-ui/table/_story/Demos/treeSelect.jsx
  packages/semi-ui/table/_story/Demos/virtualized.jsx
  packages/semi-ui/table/_story/Demos/zebra.jsx
Labels: document

#326 fix: [Select] Add key to the content returned by renderSelectedItem #320
  content/input/select/index-en-US.md
  content/input/select/index.md
  packages/semi-ui/select/_story/select.stories.js
  packages/semi-ui/select/index.tsx
Labels: bug

#197 chore(codesandbox): add codesandbox ci
  .codesandbox/ci.json
  package.json
Labels: enhancement

#330 fix(inputnumber): editor api syntax hint error #327
  packages/semi-ui/form/field.tsx
  packages/semi-ui/inputNumber/index.tsx
Labels: bug

#332 fix(input): focus hover state border color bug #234
  packages/semi-foundation/input/input.scss
  packages/semi-foundation/input/variables.scss
Labels: bug
