Repository DouyinFE/semi-design, pull requests merged in 2022-04, with the labels that each got.

#739 fix(datepicker): fixed DatePicker defaultPickerValue given number pan…
  cypress/integration/datePicker.spec.js
  packages/semi-foundation/datePicker/_utils/getDefaultPickerDate.ts
  packages/semi-foundation/datePicker/datePicker.scss
  packages/semi-ui/datePicker/_story/v2/FixDefaultPickerValue.jsx
  packages/semi-ui/datePicker/_story/v2/index.js
  packages/semi-ui/datePicker/monthsGrid.tsx
Labels: bug

#721 feat: add divider component
  packages/semi-foundation/divider/constants.ts
  packages/semi-foundation/divider/divider.scss
  packages/semi-foundation/divider/variables.scss
  packages/semi-ui/divider/__test__/divider.test.js
  packages/semi-ui/divider/_story/Demo.tsx
  packages/semi-ui/divider/_story/divider.stories.js
  packages/semi-ui/divider/_story/divider.stories.tsx
  packages/semi-ui/divider/index-en-US.md
  packages/semi-ui/divider/index.md
  packages/semi-ui/divider/index.tsx
  packages/semi-ui/index.ts
Labels: new component

#774 Fix avatar position
  packages/semi-foundation/avatar/avatar.scss
  packages/semi-foundation/avatar/rtl.scss
Labels: Style

#781 fix:(collapse) dom usless attribute
  packages/semi-ui/collapse/item.tsx
Labels: bug

#738 feat: carousel in dev
  content/order.js
  content/show/carousel/index-en-US.md
  content/show/carousel/index.md
  content/start/overview/index-en-US.md
  content/start/overview/index.md
  cypress/integration/carousel.spec.js
  packages/semi-foundation/carousel/carousel.scss
  packages/semi-foundation/carousel/constants.ts
  packages/semi-foundation/carousel/foundation.ts
  packages/semi-foundation/carousel/rtl.scss
  packages/semi-foundation/carousel/variables.scss
  packages/semi-ui/carousel/CarouselArrow.tsx
  packages/semi-ui/carousel/CarouselIndicator.tsx
  packages/semi-ui/carousel/__test__/carousel.test.js
  packages/semi-ui/carousel/_story/carousel.stories.js
  packages/semi-ui/carousel/index-en-US.md
  packages/semi-ui/carousel/index.md
  packages/semi-ui/carousel/index.tsx
  packages/semi-ui/carousel/interface.ts
  packages/semi-ui/index.ts
  src/images/docIcons/doc-carousel.svg
Labels: new component
