Repository DouyinFE/semi-design, pull requests merged in 2022-11, with the labels that each got.

#1229 feat: [Transfer] provides a search method for users to manually trigg…
  content/input/transfer/index-en-US.md
  content/input/transfer/index.md
  packages/semi-foundation/transfer/foundation.ts
  packages/semi-ui/transfer/_story/transfer.stories.jsx
  packages/semi-ui/transfer/index.tsx
Labels: codeball:needs-review

#1231 Test cypress
  .github/workflows/chromatic.yml
  .github/workflows/cypress.yml
  .github/workflows/lighthouse.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/test:coverage.yml
Labels: codeball:needs-review

#1230 A11y site support
  package.json
  packages/semi-ui/tabs/TabPane.tsx
  packages/semi-ui/tabs/interface.ts
  src/components/Footer/index.jsx
  src/components/layout.js
  src/components/side-nav.js
  src/sitePages/newHome/components/operateButton/operateButton.jsx
  src/sitePages/newHome/components/operateButton/operateButton.module.scss
  src/styles/doc.scss
  src/styles/layout.scss
  src/templates/postTemplate.js
  yarn.lock
Labels: codeball:needs-careful-review

#1235 fix: fix the wrong scroll position when table fixed column
  packages/semi-foundation/table/constants.ts
  packages/semi-foundation/table/table.scss
  packages/semi-ui/table/Body/index.tsx
  packages/semi-ui/table/Table.tsx
Labels: bug, codeball:needs-review

#1239 feat: [TagInput] Add the onClose parameter to the renderTagItem of Ta…
  content/input/taginput/index-en-US.md
  content/input/taginput/index.md
  cypress/integration/tagInput.spec.js
  packages/semi-ui/tagInput/_story/tagInput.stories.jsx
  packages/semi-ui/tagInput/index.tsx
Labels: codeball:needs-review

#1236 test: [Image] add test cases
  .gitignore
  cypress/integration/image.spec.js
  cypress/support/index.js
  packages/semi-foundation/image/imageFoundation.ts
  packages/semi-foundation/image/previewFooterFoundation.ts
  packages/semi-foundation/image/previewImageFoundation.ts
  packages/semi-foundation/image/previewInnerFoundation.ts
  packages/semi-ui/image/_story/image.stories.jsx
  packages/semi-ui/image/image.tsx
  packages/semi-ui/image/interface.tsx
  packages/semi-ui/image/preview.tsx
  packages/semi-ui/image/previewImage.tsx
  packages/semi-ui/image/previewInner.tsx
Labels: codeball:needs-review

#1243 fix: fix the wrong padding in navigation link
  cypress/integration/carousel.spec.js
  packages/semi-foundation/navigation/navigation.scss
  packages/semi-ui/navigation/Item.tsx
  src/components/side-nav.js
  src/styles/doc.scss
Labels: codeball:needs-review

#1244 style: [Cascader] The right icon in the Cascader menu item increases …
  packages/semi-foundation/cascader/cascader.scss
  packages/semi-foundation/cascader/variables.scss
  packages/semi-ui/cascader/item.tsx
Labels: codeball:needs-review

#1245 feat: add new icon
  packages/semi-icons/src/icons/IconCalendarStroked.tsx
  packages/semi-icons/src/icons/IconConfigStroked.tsx
  packages/semi-icons/src/icons/IconConnectionPoint1.tsx
  packages/semi-icons/src/icons/IconConnectionPoint2.tsx
  packages/semi-icons/src/icons/IconIssueStroked.tsx
  packages/semi-icons/src/icons/IconStoryStroked.tsx
  packages/semi-icons/src/icons/IconVersionStroked.tsx
  packages/semi-icons/src/icons/index.ts
  packages/semi-icons/src/svgs/calendar_stroked.svg
  packages/semi-icons/src/svgs/config_stroked.svg
  packages/semi-icons/src/svgs/connection_point_1.svg
  packages/semi-icons/src/svgs/connection_point_2.svg
  packages/semi-icons/src/svgs/issue_stroked.svg
  packages/semi-icons/src/svgs/meta.json
  packages/semi-icons/src/svgs/storys_stroked.svg
  packages/semi-icons/src/svgs/version_stroked.svg
  src/components/IconList/index.jsx
Labels: codeball:needs-review

#1246 docs: add the contribution steps to semi-icon package
  packages/semi-icons/CONTRIBUTING.md
Labels: codeball:needs-review

#1176 feat: new tooltip smart pos adjust
  content/show/tooltip/index-en-US.md
  content/show/tooltip/index.md
  cypress/integration/anchor.spec.js
  cypress/integration/tabs.spec.js
  cypress/integration/tooltip.spec.js
  packages/semi-foundation/tooltip/constants.ts
  packages/semi-foundation/tooltip/foundation.ts
  packages/semi-ui/table/_story/v2/stickyHeader/index.scss
  packages/semi-ui/tooltip/__test__/tooltip.test.js
  packages/semi-ui/tooltip/_story/AutoAdjustOverflow/bottom2Other.jsx
  packages/semi-ui/tooltip/_story/AutoAdjustOverflow/common.jsx
  packages/semi-ui/tooltip/_story/AutoAdjustOverflow/index.jsx
  packages/semi-ui/tooltip/_story/AutoAdjustOverflow/left2Other.jsx
  packages/semi-ui/tooltip/_story/AutoAdjustOverflow/right2Other.jsx
  packages/semi-ui/tooltip/_story/AutoAdjustOverflow/top2Other.jsx
  packages/semi-ui/tooltip/_story/InTable/index.jsx
  packages/semi-ui/tooltip/_story/story.scss
  packages/semi-ui/tooltip/_story/tooltip.stories.jsx
  packages/semi-ui/tooltip/index.tsx
  yarn.lock
Labels: codeball:needs-careful-review

#1247 fix: [Transfer] Fixed Transfer in Popover causing Popover to close wh…
  packages/semi-foundation/tagInput/tagInput.scss
  packages/semi-foundation/tagInput/variables.scss
  packages/semi-foundation/transfer/transfer.scss
  packages/semi-foundation/transfer/variables.scss
  packages/semi-theme-default/scss/variables.scss
  packages/semi-ui/tagInput/_story/tagInput.stories.jsx
  packages/semi-ui/tagInput/index.tsx
  packages/semi-ui/transfer/_story/transfer.stories.jsx
  packages/semi-ui/transfer/index.tsx
Labels: codeball:needs-review

#1258 style: fix incorrect token name of form; update token comment
  packages/semi-foundation/form/form.scss
  packages/semi-foundation/form/rtl.scss
  packages/semi-foundation/form/variables.scss
Labels: codeball:needs-review

#1255 fix: fix form in sidesheet, form constructor not mount at first trick
  packages/semi-foundation/modal/modalFoundation.ts
  packages/semi-foundation/sideSheet/sideSheetFoundation.ts
  packages/semi-ui/modal/Modal.tsx
  packages/semi-ui/sideSheet/index.tsx
Labels: codeball:approved

#1251 [Tabs] Tabs add token
  packages/semi-foundation/tabs/tabs.scss
  packages/semi-foundation/tabs/variables.scss
Labels: codeball:needs-review

#1260 fix: fix click dropdown make screen scroll after tooltip add off screen render
  packages/semi-foundation/dropdown/foundation.ts
  packages/semi-foundation/dropdown/menuFoundation.ts
  packages/semi-foundation/tooltip/foundation.ts
  packages/semi-ui/datePicker/yearAndMonth.tsx
  packages/semi-ui/dropdown/dropdownMenu.tsx
  packages/semi-ui/dropdown/index.tsx
  packages/semi-ui/tooltip/index.tsx
Labels: codeball:needs-careful-review

#1259 fix: replace animation token with none token
  packages/semi-foundation/anchor/animation.scss
  packages/semi-foundation/autoComplete/animation.scss
  packages/semi-foundation/breadcrumb/animation.scss
  packages/semi-foundation/button/animation.scss
  packages/semi-foundation/carousel/animation.scss
  packages/semi-foundation/cascader/animation.scss
  packages/semi-foundation/checkbox/animation.scss
  packages/semi-foundation/collapsible/animation.scss
  packages/semi-foundation/datePicker/animation.scss
  packages/semi-foundation/dropdown/animation.scss
  packages/semi-foundation/input/animation.scss
  packages/semi-foundation/inputNumber/animation.scss
  packages/semi-foundation/navigation/animation.scss
  packages/semi-foundation/pagination/animation.scss
  packages/semi-foundation/radio/animation.scss
  packages/semi-foundation/rating/animation.scss
  packages/semi-foundation/scrollList/animation.scss
  packages/semi-foundation/select/animation.scss
  packages/semi-foundation/slider/animation.scss
  packages/semi-foundation/steps/animation.scss
  packages/semi-foundation/switch/animation.scss
  packages/semi-foundation/table/animation.scss
  packages/semi-foundation/tabs/animation.scss
  packages/semi-foundation/tagInput/animation.scss
  packages/semi-foundation/timePicker/utils/animation.scss
  packages/semi-foundation/transfer/animation.scss
  packages/semi-foundation/tree/animation.scss
  packages/semi-theme-default/scss/animation.scss
Labels: codeball:approved

#1265 fix: remove useless setPaddingLeft call in input, close #1262, 1181
  packages/semi-foundation/input/foundation.ts
  packages/semi-ui/input/index.tsx
Labels: codeball:approved

#1267 feat: add switch token
  gatsby-node.js
  packages/semi-foundation/switch/rtl.scss
  packages/semi-foundation/switch/switch.scss
  packages/semi-foundation/switch/variables.scss
Labels: codeball:approved

#1272 Fix form token extra
  content/start/changelog/index-en-US.md
  content/start/changelog/index.md
  packages/semi-foundation/form/form.scss
  packages/semi-foundation/form/variables.scss
Labels: codeball:needs-review

#1249 feat: nav add react-router support
  content/navigation/navigation/index-en-US.md
  content/navigation/navigation/index.md
  packages/semi-ui/navigation/Item.tsx
  packages/semi-ui/navigation/index.tsx
  packages/semi-ui/navigation/nav-context.ts
Labels: codeball:needs-review

#1279 fix: switch add more token
  packages/semi-foundation/switch/rtl.scss
  packages/semi-foundation/switch/switch.scss
  packages/semi-foundation/switch/variables.scss
Labels: codeball:approved

#1276 fix: single select will flush when filter is true, close #1207
  .vscode/launch.json
  packages/semi-foundation/select/foundation.ts
  packages/semi-foundation/utils/Event.ts
  packages/semi-ui/select/_story/select.stories.jsx
  packages/semi-ui/select/index.tsx
Labels: codeball:needs-careful-review

#1266 Feat field props name
  content/input/form/index-en-US.md
  content/input/form/index.md
  packages/semi-ui/form/_story/FieldProps/name.jsx
  packages/semi-ui/form/_story/form.stories.jsx
  packages/semi-ui/form/hoc/withField.tsx
Labels: feature request, codeball:needs-careful-review

#1278 style: [Cascader/TreeSelect] Modify the style of TagInput used in Cas…
  packages/semi-foundation/cascader/cascader.scss
  packages/semi-foundation/cascader/variables.scss
  packages/semi-foundation/tagInput/tagInput.scss
  packages/semi-foundation/treeSelect/treeSelect.scss
  packages/semi-foundation/treeSelect/variables.scss
  packages/semi-ui/cascader/_story/cascader.stories.jsx
  packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
Labels: codeball:needs-careful-review

#1290 Feat/image crossorigin
  content/show/image/index.md
  packages/semi-ui/image/image.tsx
  packages/semi-ui/image/index.tsx
  packages/semi-ui/image/interface.tsx
  packages/semi-ui/image/previewImage.tsx
  packages/semi-ui/image/previewInner.tsx
Labels: codeball:needs-review

#1282 Nav add getPopupContainer
  content/navigation/navigation/index-en-US.md
  content/navigation/navigation/index.md
  content/start/dark-mode/index-en-US.md
  content/start/dark-mode/index.md
  packages/semi-ui/navigation/SubNav.tsx
  packages/semi-ui/navigation/_story/Popup/index.jsx
  packages/semi-ui/navigation/_story/navigation.stories.jsx
  packages/semi-ui/navigation/index.tsx
  packages/semi-ui/navigation/nav-context.ts
Labels: feature request, codeball:needs-review

#1281 New Component Highlight
  content/feedback/banner/index-en-US.md
  content/feedback/banner/index.md
  content/feedback/notification/index-en-US.md
  content/feedback/notification/index.md
  content/feedback/popconfirm/index-en-US.md
  content/feedback/popconfirm/index.md
  content/feedback/progress/index-en-US.md
  content/feedback/progress/index.md
  content/feedback/skeleton/index-en-US.md
  content/feedback/skeleton/index.md
  content/feedback/spin/index-en-US.md
  content/feedback/spin/index.md
  content/feedback/toast/index-en-US.md
  content/feedback/toast/index.md
  content/order.js
  content/other/configprovider/index-en-US.md
  content/other/configprovider/index.md
  content/other/locale/index-en-US.md
  content/other/locale/index.md
  content/show/highlight/index-en-US.md
  content/show/highlight/index.md
  content/show/image/index-en-US.md
  content/show/image/index.md
  content/show/list/index-en-US.md
  content/show/list/index.md
  content/show/modal/index-en-US.md
  content/show/modal/index.md
  content/show/overflowlist/index-en-US.md
  content/show/overflowlist/index.md
  content/show/popover/index-en-US.md
  content/show/popover/index.md
  content/show/scrolllist/index-en-US.md
  content/show/scrolllist/index.md
  content/show/sidesheet/index-en-US.md
  content/show/sidesheet/index.md
  content/show/table/index-en-US.md
  content/show/table/index.md
  content/show/tag/index-en-US.md
  content/show/tag/index.md
  content/show/timeline/index-en-US.md
  content/show/timeline/index.md
  content/show/tooltip/index-en-US.md
  content/show/tooltip/index.md
  content/start/overview/index-en-US.md
  content/start/overview/index.md
  gatsby-node.js
  packages/semi-foundation/highlight/constants.ts
  packages/semi-foundation/highlight/highlight.scss
  packages/semi-foundation/highlight/variables.scss
  packages/semi-ui/_utils/index.tsx
  packages/semi-ui/highlight/_story/highlight.stories.jsx
  packages/semi-ui/highlight/_story/highlight.stories.tsx
  packages/semi-ui/highlight/index-en-US.md
  packages/semi-ui/highlight/index.md
  packages/semi-ui/highlight/index.tsx
  packages/semi-ui/index.ts
  packages/semi-ui/select/_story/select.stories.jsx
  src/images/docIcons/doc-highlight.svg
Labels: feature request, codeball:needs-careful-review

#1297 fix: fix the problem when trigger be blocked the wrapper did not offset
  packages/semi-foundation/tooltip/foundation.ts
  packages/semi-ui/tooltip/_story/tooltip.stories.jsx
Labels: codeball:needs-review

#1298 fix: [Image] Fix the problem that the custom Header cannot be display…
  packages/semi-ui/image/preview.tsx
Labels: codeball:needs-review

#1294 Fix/input ref
  cypress/integration/datePicker.spec.js
  cypress/integration/input.spec.js
  cypress/integration/inputNumber.spec.js
  packages/semi-foundation/input/foundation.ts
  packages/semi-foundation/inputNumber/foundation.ts
  packages/semi-ui/input/_story/input.stories.jsx
  packages/semi-ui/input/index.tsx
  packages/semi-ui/inputNumber/__test__/inputNumber.test.js
  packages/semi-ui/inputNumber/_story/inputNumber.stories.jsx
Labels: codeball:needs-careful-review

#1296 fix: change the scrollIntoView inline parameter to align the behavior in arrow and item click
  packages/semi-ui/tabs/TabBar.tsx
Labels: codeball:needs-review

#1303 docs: improve toast api usage
  content/feedback/toast/index-en-US.md
  content/feedback/toast/index.md
Labels: codeball:needs-review

#1304 fix: [TreeSelect] Fix when searchAutoFocus is true and searchPosition…
  packages/semi-ui/treeSelect/index.tsx
Labels: codeball:approved

#1308 fix: DatePicker disabledDate interaction is not easy to use when type…
  cypress/integration/datePicker.spec.js
  packages/semi-foundation/datePicker/yearAndMonthFoundation.ts
  packages/semi-ui/datePicker/_story/v2/FixDisabledMonth.tsx
  packages/semi-ui/datePicker/_story/v2/index.js
  packages/semi-ui/datePicker/yearAndMonth.tsx
Labels: codeball:needs-review
