Repository DouyinFE/semi-design, pull requests merged in 2022-08, with the labels that each got.

#1018 fix: fix the problem that letters and numbers cannot be entered when …
  packages/semi-foundation/dropdown/menuFoundation.ts
Labels: bug

#1012 feat: add position option to preset panel
  content/input/datepicker/index-en-US.md
  content/input/datepicker/index.md
  packages/semi-foundation/datePicker/constants.ts
  packages/semi-foundation/datePicker/datePicker.scss
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-foundation/datePicker/monthsGridFoundation.ts
  packages/semi-foundation/datePicker/rtl.scss
  packages/semi-foundation/datePicker/variables.scss
  packages/semi-foundation/datePicker/yearAndMonthFoundation.ts
  packages/semi-ui/datePicker/_story/datePicker.stories.js
  packages/semi-ui/datePicker/datePicker.tsx
  packages/semi-ui/datePicker/monthsGrid.tsx
  packages/semi-ui/datePicker/quickControl.tsx
  packages/semi-ui/datePicker/yearAndMonth.tsx
Labels: feature request

#1040 fix: set the outer div's props tabindex to -1, and when value change …
  packages/semi-foundation/autoComplete/foundation.ts
  packages/semi-ui/autoComplete/index.tsx
Labels: bug

#1049 [Feat] Support auto append form label optional text
  content/input/form/index-en-US.md
  content/input/form/index.md
  packages/semi-foundation/form/form.scss
  packages/semi-foundation/form/variables.scss
  packages/semi-ui/form/_story/FieldProps/labelOptional.jsx
  packages/semi-ui/form/_story/form.stories.js
  packages/semi-ui/form/hoc/withField.tsx
  packages/semi-ui/form/label.tsx
  packages/semi-ui/locale/interface.ts
  packages/semi-ui/locale/source/ar.ts
  packages/semi-ui/locale/source/de.ts
  packages/semi-ui/locale/source/en_GB.ts
  packages/semi-ui/locale/source/en_US.ts
  packages/semi-ui/locale/source/es.ts
  packages/semi-ui/locale/source/fr.ts
  packages/semi-ui/locale/source/id_ID.ts
  packages/semi-ui/locale/source/it.ts
  packages/semi-ui/locale/source/ja_JP.ts
  packages/semi-ui/locale/source/ko_KR.ts
  packages/semi-ui/locale/source/ms_MY.ts
  packages/semi-ui/locale/source/pt_BR.ts
  packages/semi-ui/locale/source/ru_RU.ts
  packages/semi-ui/locale/source/th_TH.ts
  packages/semi-ui/locale/source/tr_TR.ts
  packages/semi-ui/locale/source/vi_VN.ts
  packages/semi-ui/locale/source/zh_CN.ts
  packages/semi-ui/locale/source/zh_TW.ts
Labels: feature request

#1064 fix: fix the problem when react 18 and strict mode useFormApi get null
  packages/semi-ui/form/baseForm.tsx
Labels: codeball:needs-review

#1069 docs: Optimizing the usage example of color API
  content/show/tag/index-en-US.md
  content/show/tag/index.md
Labels: codeball:approved

#1066 fix: fix the left of the emptyContent parameter of Transfer does not …
  packages/semi-ui/transfer/index.tsx
Labels: codeball:needs-review

#1070 docs: add Faq to popover
  content/show/popover/index-en-US.md
  content/show/popover/index.md
Labels: codeball:needs-review

#1067 fix: make collapse icon fixed to avoid the collapse tabs flush in some width
  cypress/integration/tabs.spec.js
  packages/semi-ui/tabs/TabBar.tsx
Labels: bug, codeball:needs-review

#1071 docs: add Faq to popover/popconfirm/dropdown
  content/feedback/popconfirm/index-en-US.md
  content/feedback/popconfirm/index.md
  content/show/dropdown/index-en-US.md
  content/show/dropdown/index.md
  content/show/popover/index-en-US.md
  content/show/popover/index.md
Labels: codeball:needs-review

#1059 feat: popconfirm onOk,onCancel support promise return, async close, c…
  content/feedback/popconfirm/index-en-US.md
  content/feedback/popconfirm/index.md
  packages/semi-foundation/popconfirm/popconfirmFoundation.ts
  packages/semi-ui/popconfirm/_story/popconfirm.stories.js
  packages/semi-ui/popconfirm/index.tsx
Labels: codeball:needs-review

#1074 fix: table scss remove simple format token
  packages/semi-foundation/table/mixin.scss
  packages/semi-foundation/table/rtl.scss
  packages/semi-foundation/table/table.scss
  packages/semi-foundation/table/variables.scss
Labels: codeball:needs-review

#1060 refactor: radio style
  packages/semi-foundation/radio/radio.scss
  packages/semi-foundation/radio/rtl.scss
  packages/semi-ui/radio/_story/radio.stories.js
  packages/semi-ui/radio/radio.tsx
  packages/semi-ui/radio/radioGroup.tsx
Labels: codeball:needs-review

#1065 refactor: button group line
  packages/semi-foundation/button/button.scss
  packages/semi-foundation/button/variables.scss
  packages/semi-ui/button/buttonGroup.tsx
  packages/semi-ui/button/index.tsx
Labels: codeball:needs-review

#1073 Refactor checkbox
  packages/semi-foundation/checkbox/checkbox.scss
  packages/semi-foundation/checkbox/rtl.scss
  packages/semi-ui/checkbox/_story/checkbox.stories.js
  packages/semi-ui/checkbox/checkbox.tsx
  packages/semi-ui/checkbox/checkboxGroup.tsx
Labels: codeball:needs-review

#1080 chore: add elementType to Checkbox,Radio,Avatar
  packages/semi-ui/avatar/index.tsx
  packages/semi-ui/checkbox/checkbox.tsx
  packages/semi-ui/radio/radio.tsx
Labels: codeball:approved

#1084 fix: TreeSelect and Transfer CheckboxGroup row-gap bug #1073
  packages/semi-foundation/tree/tree.scss
  packages/semi-ui/transfer/_story/transfer.stories.js
  packages/semi-ui/treeSelect/_story/treeSelect.stories.js
Labels: codeball:needs-review

#1081 fix: tag tagKey propType
  packages/semi-ui/tag/index.tsx
Labels: codeball:approved
