Repository DouyinFE/semi-design, pull requests merged in 2022-12, with the labels that each got.

#1291 fix: remove focus state update when tag close in multiple select
  packages/semi-foundation/select/foundation.ts
Labels: codeball:needs-careful-review

#1321 feat: add hover and active color to tag close
  packages/semi-foundation/tag/tag.scss
  packages/semi-foundation/tag/variables.scss
Labels: codeball:needs-review

#1323 chore: update withFormState、withFormApi type define
  packages/semi-ui/form/_story/form.stories.tsx
  packages/semi-ui/form/hoc/withFormApi.tsx
  packages/semi-ui/form/hoc/withFormState.tsx
Labels: codeball:needs-review

#1334 feat: pass redundant parameters in Image to img node
  package.json
  packages/semi-ui/image/_story/image.stories.tsx
  packages/semi-ui/image/image.tsx
Labels: codeball:needs-review

#1333 fix: disabled switch can't trigger mouseLeave, tooltip can't hide
  packages/semi-foundation/switch/switch.scss
Labels: codeball:approved

#1337 fix: Fix the problem that the same id in multiple svgs causes incorre…
  packages/semi-icons/src/icons/IconLoading.tsx
  packages/semi-icons/src/icons/IconSpin.tsx
  packages/semi-icons/src/icons/IconTriangleArrow.tsx
  packages/semi-icons/src/icons/IconUserAdd.tsx
  packages/semi-icons/src/svgs/loading.svg
  packages/semi-icons/src/svgs/spin.svg
  packages/semi-icons/src/svgs/triangle_arrow.svg
  packages/semi-icons/src/svgs/user_add.svg
  packages/semi-illustrations/src/illustrations/IllustrationFailure.tsx
  packages/semi-illustrations/src/illustrations/IllustrationFailureDark.tsx
  packages/semi-illustrations/src/svgs/failure-dark.svg
  packages/semi-illustrations/src/svgs/failure.svg
Labels: codeball:approved

#684 perf(overflowlist): optimize collapse rendering
  cypress/integration/overflowList.spec.js
  packages/semi-foundation/overflowList/constants.ts
  packages/semi-foundation/overflowList/foundation.ts
  packages/semi-ui/overflowList/__test__/overflowList.test.js
  packages/semi-ui/overflowList/_story/overflowList.stories.jsx
  packages/semi-ui/overflowList/index.tsx
Labels: codeball:needs-careful-review

#1340 fix: [Select] Fix the problem that there is still a drop-down box whe…
  cypress/integration/select.spec.js
  packages/semi-ui/select/_story/select.stories.jsx
  packages/semi-ui/select/index.tsx
Labels: codeball:needs-review

#1339 fix: [TagInput] Fix the wrong style of TagInput when it is draggable
  packages/semi-foundation/cascader/cascader.scss
  packages/semi-foundation/tagInput/tagInput.scss
  packages/semi-foundation/treeSelect/treeSelect.scss
  packages/semi-ui/cascader/_story/cascader.stories.jsx
  packages/semi-ui/tag/_story/tag.stories.jsx
  packages/semi-ui/tag/index.tsx
  packages/semi-ui/tagInput/index.tsx
Labels: codeball:needs-review

#1344 fix: fix the problem that the automatic adjustment position is incorrect when the position is topleft
  packages/semi-foundation/tooltip/foundation.ts
Labels: codeball:approved

#1329 feat(table): support empty filters #1201
  cypress/integration/table.spec.js
  packages/semi-foundation/table/foundation.ts
  packages/semi-foundation/table/utils.ts
  packages/semi-ui/table/Table.tsx
  packages/semi-ui/table/_story/v2/emptyFilters.tsx
  packages/semi-ui/table/_story/v2/index.js
Labels: codeball:needs-review

#1330 fix: [TreeSelect] Fix TypeError in TreeSelect when checkRelation = un…
  packages/semi-foundation/tree/treeUtil.ts
  packages/semi-foundation/treeSelect/foundation.ts
  packages/semi-ui/treeSelect/__test__/treeMultiple.test.js
  packages/semi-ui/treeSelect/__test__/treeSelect.test.js
  packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
  packages/semi-ui/treeSelect/index.tsx
Labels: codeball:needs-careful-review

#1346 fix: [TagInput] Fix max Length judgment is wrong in composition input
  packages/semi-foundation/tagInput/foundation.ts
  packages/semi-ui/tagInput/_story/tagInput.stories.jsx
  packages/semi-ui/tagInput/index.tsx
Labels: codeball:needs-review
