Repository DouyinFE/semi-design, pull requests merged in 2022-09, with the labels that each got.

#1089 docs: change complex api type show
  content/input/datepicker/index-en-US.md
  content/input/datepicker/index.md
  src/components/ApiType/index.tsx
  src/templates/postTemplate.js
Labels: codeball:needs-review

#1093 fix: fix slider #1043
  packages/semi-foundation/slider/foundation.ts
Labels: codeball:needs-review

#1086 fix: [Form] Fix the problem of setting autoComplete to false at the F…
  content/input/form/index-en-US.md
  content/input/form/index.md
  packages/semi-ui/form/interface.ts
Labels: codeball:needs-review

#1097 fix: [tagGroup] Move the inteface declaration to interface.ts
  packages/semi-ui/tag/group.tsx
  packages/semi-ui/tag/interface.ts
Labels: codeball:needs-review

#1100 fix: fix the repeat declare problem
  packages/semi-ui/transfer/_story/transfer.stories.js
Labels: codeball:needs-review

#1077 fix: fix defaultTabBar type error
  packages/semi-ui/tabs/_story/Demo.tsx
  packages/semi-ui/tabs/interface.ts
Labels: bug, codeball:needs-review

#1098 style: sidesheet body add overflow: auto
  packages/semi-foundation/sideSheet/sideSheet.scss
Labels: codeball:approved

#1109 chore: remove corejs
  packages/semi-animation-react/getBabelConfig.js
  packages/semi-animation-react/package.json
  packages/semi-animation/getBabelConfig.js
  packages/semi-animation/package.json
  packages/semi-foundation/getBabelConfig.js
  packages/semi-foundation/package.json
  packages/semi-ui/getBabelConfig.js
  packages/semi-ui/package.json
Labels: codeball:needs-review

#1103 fix: fix the trigger in dropdown do not response the enter press problem
  packages/semi-foundation/dropdown/foundation.ts
  packages/semi-foundation/dropdown/menuFoundation.ts
  packages/semi-ui/dropdown/index.tsx
  packages/semi-ui/tooltip/index.tsx
Labels: bug, codeball:needs-review

#1113 fix: fix event render didn't change with weekStartsOn
  packages/semi-foundation/calendar/eventUtil.ts
  packages/semi-foundation/calendar/foundation.ts
  packages/semi-ui/calendar/_story/calendar.stories.js
Labels: bug, codeball:needs-review

#1111 fix: fix the problem that when panel is close the onblur function no …
  packages/semi-foundation/select/foundation.ts
Labels: codeball:approved

#1116 fix: after update the anchor click area, a11y offset should be internal
  packages/semi-foundation/anchor/anchor.scss
  packages/semi-foundation/anchor/variables.scss
Labels: codeball:needs-review

#1121 Token table add animation
  .vscode/settings.json
  content/basic/tokens/index-en-US.md
  content/basic/tokens/index.md
  scripts/designToken.js
  src/components/DesignToken/index.tsx
Labels: codeball:needs-review

#1122 Change animation import order
  packages/semi-foundation/anchor/anchor.scss
  packages/semi-foundation/autoComplete/autoComplete.scss
  packages/semi-foundation/breadcrumb/breadcrumb.scss
  packages/semi-foundation/button/button.scss
  packages/semi-foundation/carousel/carousel.scss
  packages/semi-foundation/cascader/cascader.scss
  packages/semi-foundation/checkbox/checkbox.scss
  packages/semi-foundation/dropdown/dropdown.scss
  packages/semi-foundation/input/input.scss
  packages/semi-foundation/input/textarea.scss
  packages/semi-foundation/inputNumber/inputNumber.scss
  packages/semi-foundation/inputNumber/variables.scss
  packages/semi-foundation/navigation/navigation.scss
  packages/semi-foundation/pagination/pagination.scss
  packages/semi-foundation/radio/radio.scss
  packages/semi-foundation/rating/rating.scss
  packages/semi-foundation/scrollList/scrollList.scss
  packages/semi-foundation/select/select.scss
  packages/semi-foundation/sideSheet/sideSheet.scss
  packages/semi-foundation/slider/slider.scss
  packages/semi-foundation/steps/steps.scss
  packages/semi-foundation/switch/switch.scss
  packages/semi-foundation/table/table.scss
  packages/semi-foundation/tabs/tabs.scss
  packages/semi-foundation/tagInput/tagInput.scss
  packages/semi-foundation/transfer/transfer.scss
  packages/semi-foundation/tree/tree.scss
Labels: codeball:needs-careful-review

#1120 Chore remove source code
  lerna.json
  packages/semi-animation-react/package.json
  packages/semi-animation-styled/package.json
  packages/semi-animation/package.json
  packages/semi-eslint-plugin/package.json
  packages/semi-foundation/package.json
  packages/semi-icons/package.json
  packages/semi-illustrations/package.json
  packages/semi-next/package.json
  packages/semi-scss-compile/package.json
  packages/semi-theme-default/package.json
  packages/semi-ui/package.json
  packages/semi-webpack/package.json
Labels: codeball:needs-review

#1106 feat:[Toast] Support change toast content by id.
  content/feedback/toast/index-en-US.md
  content/feedback/toast/index.md
  package.json
  packages/semi-foundation/toast/toastListFoundation.ts
  packages/semi-ui/toast/__test__/toast.test.js
  packages/semi-ui/toast/_story/toast.stories.js
  packages/semi-ui/toast/index.tsx
  packages/semi-ui/toast/toast.tsx
Labels: codeball:needs-review

#1129 feat: add shape option to tag
  content/show/tag/index-en-US.md
  content/show/tag/index.md
  packages/semi-foundation/tag/tag.scss
  packages/semi-foundation/tag/variables.scss
  packages/semi-ui/tag/_story/tag.stories.js
  packages/semi-ui/tag/index.tsx
  packages/semi-ui/tag/interface.ts
Labels: codeball:needs-review

#1130 [Fix]: replace divide operator to math.div
  package.json
  packages/semi-animation-styled/getBabelConfig.js
  packages/semi-animation-styled/package.json
  packages/semi-foundation/badge/badge.scss
  packages/semi-foundation/calendar/variables.scss
  packages/semi-foundation/datePicker/variables.scss
  packages/semi-foundation/form/variables.scss
  packages/semi-foundation/grid/grid.scss
  packages/semi-foundation/grid/mixin.scss
  packages/semi-foundation/gulpfile.js
  packages/semi-foundation/navigation/variables.scss
  packages/semi-foundation/package.json
  packages/semi-foundation/radio/variables.scss
  packages/semi-foundation/scrollList/scrollList.scss
  packages/semi-foundation/scrollList/variables.scss
  packages/semi-foundation/switch/switch.scss
  packages/semi-foundation/switch/variables.scss
  packages/semi-foundation/tag/tag.scss
  packages/semi-icons/package.json
  packages/semi-scss-compile/package.json
  packages/semi-ui/package.json
  packages/semi-webpack/package.json
  yarn.lock
Labels: codeball:needs-careful-review

#1139 docs: update faq in modal
  content/show/modal/index-en-US.md
  content/show/modal/index.md
Labels: codeball:approved

#1143 chore: add export type keyword for interface
  packages/semi-foundation/calendar/foundation.ts
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-foundation/navigation/foundation.ts
  packages/semi-ui/anchor/index.tsx
  packages/semi-ui/backtop/index.tsx
  packages/semi-ui/breadcrumb/index.tsx
  packages/semi-ui/breadcrumb/item.tsx
  packages/semi-ui/button/index.tsx
  packages/semi-ui/calendar/index.tsx
  packages/semi-ui/calendar/interface.ts
  packages/semi-ui/card/index.tsx
  packages/semi-ui/cascader/index.tsx
  packages/semi-ui/checkbox/index.tsx
  packages/semi-ui/collapse/index.tsx
  packages/semi-ui/datePicker/index.tsx
  packages/semi-ui/descriptions/index.tsx
  packages/semi-ui/dropdown/dropdownItem.tsx
  packages/semi-ui/dropdown/index.tsx
  packages/semi-ui/form/arrayField.tsx
  packages/semi-ui/form/index.tsx
  packages/semi-ui/grid/index.tsx
  packages/semi-ui/icons/index.tsx
  packages/semi-ui/input/index.tsx
  packages/semi-ui/layout/index.tsx
  packages/semi-ui/list/index.tsx
  packages/semi-ui/modal/Modal.tsx
  packages/semi-ui/modal/index.tsx
  packages/semi-ui/navigation/index.tsx
  packages/semi-ui/notification/index.tsx
  packages/semi-ui/overflowList/index.tsx
  packages/semi-ui/pagination/index.tsx
  packages/semi-ui/popover/index.tsx
  packages/semi-ui/radio/index.tsx
  packages/semi-ui/radio/radio.tsx
  packages/semi-ui/rating/index.tsx
  packages/semi-ui/scrollList/index.tsx
  packages/semi-ui/select/index.tsx
  packages/semi-ui/sideSheet/index.tsx
  packages/semi-ui/skeleton/index.tsx
  packages/semi-ui/slider/index.tsx
  packages/semi-ui/steps/index.tsx
  packages/semi-ui/timePicker/index.tsx
  packages/semi-ui/timeline/index.tsx
  packages/semi-ui/toast/index.tsx
  packages/semi-ui/tooltip/index.tsx
  packages/semi-ui/tree/index.tsx
  packages/semi-ui/typography/index.tsx
  packages/semi-ui/upload/index.tsx
Labels: codeball:needs-review

#1126 fix: [Select] Fixed the problem that Select did not focus on the firs…
  packages/semi-foundation/select/foundation.ts
Labels: codeball:approved

#1133 fix: Fix the redundant box-shadow in the fixed column on the left whe…
  packages/semi-ui/table/Table.tsx
Labels: codeball:needs-review

#1146 Fix: [Image] fix the drag and drop problem after the Image component is enlarged
  content/show/dropdown/index-en-US.md
  content/show/image/index-en-US.md
  content/show/image/index.md
  packages/semi-foundation/image/image.scss
  packages/semi-foundation/image/previewImageFoundation.ts
  packages/semi-foundation/image/previewInnerFoundation.ts
  packages/semi-foundation/image/utils.ts
Labels: codeball:needs-careful-review

#1138 fix: [Button] Fix ButtonGroup does not support style
  content/input/button/index-en-US.md
  content/input/button/index.md
  packages/semi-ui/button/buttonGroup.tsx
Labels: codeball:needs-review

#1137 fix: [Tree] fix the expansion of the controlled tree is unsuccessful …
  packages/semi-ui/tree/_story/tree.stories.js
  packages/semi-ui/tree/index.tsx
Labels: codeball:needs-review

#1151 style: [Image] The image global variable plus !default for fault tole…
  packages/semi-foundation/image/variables.scss
Labels: codeball:needs-review

#1152 Upload open file select dialog manually
  content/input/upload/index-en-US.md
  content/input/upload/index.md
  packages/semi-ui/upload/_story/upload.stories.js
  packages/semi-ui/upload/index.tsx
Labels: feature request, codeball:needs-review

#1155 Fix layout effect ssr warning
  packages/semi-ui/form/_story/DynamicField/arrayFieldDemo.jsx
  packages/semi-ui/form/hoc/withField.tsx
Labels: codeball:needs-careful-review

#1159 fix: ts error in high typescipt version && modal focus logic
  content/start/changelog/index-en-US.md
  content/start/changelog/index.md
  packages/semi-foundation/tree/foundation.ts
  packages/semi-ui/breadcrumb/item.tsx
  packages/semi-ui/dropdown/index.tsx
  packages/semi-ui/modal/ModalContent.tsx
  packages/semi-ui/navigation/Footer.tsx
  packages/semi-ui/navigation/OpenIconTransition.tsx
  packages/semi-ui/navigation/SubNav.tsx
  packages/semi-ui/table/Body/index.tsx
  packages/semi-ui/timeline/index.tsx
Labels: codeball:needs-careful-review

#1153 add onkeydown to AutoComplete
  content/input/autocomplete/index-en-US.md
  content/input/autocomplete/index.md
  packages/semi-foundation/autoComplete/foundation.ts
  packages/semi-ui/autoComplete/_story/autoComplete.stories.js
  packages/semi-ui/autoComplete/index.tsx
Labels: codeball:needs-review

#1157 feat: Table add sticky API
  content/show/table/index-en-US.md
  content/show/table/index.md
  packages/semi-foundation/table/table.scss
  packages/semi-ui/table/HeadTable.tsx
  packages/semi-ui/table/Table.tsx
  packages/semi-ui/table/_story/v2/index.js
  packages/semi-ui/table/_story/v2/stickyHeader/index.scss
  packages/semi-ui/table/_story/v2/stickyHeader/index.tsx
  packages/semi-ui/table/interface.ts
  src/demos/StickyHeaderTable/index.tsx
  src/templates/postTemplate.js
Labels: codeball:needs-careful-review
