Repository DouyinFE/semi-design, pull requests merged in 2022-01, with the labels that each got.

#479 feat: a11y - improve form & field component aria, #205
  content/input/form/index.md
  content/show/popover/index-en-US.md
  content/show/popover/index.md
  packages/semi-foundation/form/utils.ts
  packages/semi-ui/autoComplete/index.tsx
  packages/semi-ui/cascader/index.tsx
  packages/semi-ui/checkbox/checkbox.tsx
  packages/semi-ui/checkbox/checkboxGroup.tsx
  packages/semi-ui/checkbox/checkboxInner.tsx
  packages/semi-ui/configProvider/_story/configProvider.stories.tsx
  packages/semi-ui/datePicker/datePicker.tsx
  packages/semi-ui/form/_story/FormApi/formApiDemo.jsx
  packages/semi-ui/form/_story/demo.jsx
  packages/semi-ui/form/_story/form.stories.js
  packages/semi-ui/form/baseForm.tsx
  packages/semi-ui/form/errorMessage.tsx
  packages/semi-ui/form/hoc/withField.tsx
  packages/semi-ui/form/interface.ts
  packages/semi-ui/form/label.tsx
  packages/semi-ui/input/index.tsx
  packages/semi-ui/inputNumber/index.tsx
  packages/semi-ui/radio/radioGroup.tsx
  packages/semi-ui/rating/index.tsx
  packages/semi-ui/select/index.tsx
  packages/semi-ui/switch/index.tsx
  packages/semi-ui/timePicker/TimePicker.tsx
  packages/semi-ui/tooltip/index.tsx
  packages/semi-ui/tree/index.tsx
  packages/semi-ui/treeSelect/index.tsx
  src/components/Footer/index.jsx
  src/sitePages/newHome/components/banner/banner.jsx
Labels: 🛠 Work In Progress

#496 fix: [TagInput] set value to falsely has no effect #483
  content/input/taginput/index-en-US.md
  content/input/taginput/index.md
  packages/semi-ui/tagInput/__test__/tagInput.test.js
  packages/semi-ui/tagInput/index.tsx
Labels: bug

#499 fix: [TreeSelect]maxTagCount does not take effect when searchPosition…
  packages/semi-ui/treeSelect/__test__/treeMultiple.test.js
  packages/semi-ui/treeSelect/_story/treeSelect.stories.js
  packages/semi-ui/treeSelect/index.tsx
Labels: bug

#500 fix: [Tree] The event passed by handleNodeDragOver to calcDropRelativ…
  packages/semi-foundation/tree/foundation.ts
Labels: bug

#423 feat(a11y): timeline aria
  content/show/timeline/index-en-US.md
  content/show/timeline/index.md
  packages/semi-ui/timeline/_story/timeline.stories.js
  packages/semi-ui/timeline/index.tsx
  packages/semi-ui/timeline/item.tsx
Labels: 🛠 Work In Progress

#424 feat(a11y): pagination aria
  content/navigation/pagination/index-en-US.md
  content/navigation/pagination/index.md
  packages/semi-ui/pagination/index.tsx
Labels: 🛠 Work In Progress

#517 fix: avoid forceUpdate call when batchUpdate by formApi.setValue/setE…
  packages/semi-foundation/form/foundation.ts
Labels: bug

#529 fix: [Tree] Scrolling items jitters when using both virtualize and re…
  packages/semi-ui/tree/treeNode.tsx
Labels: bug

#553 feat: add theme switcher trigger
  gatsby-node.js
  package.json
  src/html.js
  yarn.lock
Labels: 🌐 Website

#523 fix(table): page back to one when columns change #381
  cypress/integration/table.spec.js
  packages/semi-ui/table/Table.tsx
  packages/semi-ui/table/_story/table.stories.js
  packages/semi-ui/table/_story/v2/FixedColumnsChange/index.jsx
Labels: bug

#571 feat: add support for `onChangeWithDateFirst` API
  content/input/timepicker/index-en-US.md
  content/input/timepicker/index.md
  packages/semi-foundation/timePicker/foundation.ts
  packages/semi-ui/timePicker/TimePicker.tsx
  packages/semi-ui/timePicker/__test__/timePicker.test.js
  packages/semi-ui/timePicker/_story/timepicker.stories.js
Labels: feature request
