Repository DouyinFE/semi-design, pull requests merged in 2022-10, with the labels that each got.

#1160 fix: only when input is not null, select should notifySearch and upda…
  packages/semi-foundation/select/foundation.ts
Labels: codeball:approved

#1156 style: add rounded corners to square Avatar
  packages/semi-foundation/avatar/avatar.scss
  packages/semi-foundation/avatar/variables.scss
Labels: codeball:needs-review

#1165 fix: [carousel] Fix the problem that the timer is not updated when ca…
  packages/semi-foundation/carousel/foundation.ts
Labels: codeball:needs-careful-review

#1163 fix: dropdown onkeydown get null event
  packages/semi-ui/dropdown/index.tsx
Labels: codeball:needs-review

#1170 fix: [Image] fix scss not imported in ImagePreview
  packages/semi-ui/image/image.tsx
  packages/semi-ui/image/index.tsx
Labels: codeball:needs-review

#1171 fix: [AutoComplete] Fix AutoComplete e.target is null in onBlur callback
  packages/semi-foundation/autoComplete/foundation.ts
Labels: codeball:approved

#1175 chore: fix only use IamgePreview will lost css in webpack project
  content/start/changelog/index-en-US.md
  content/start/changelog/index.md
  packages/semi-ui/image/image.tsx
  packages/semi-ui/image/preview.tsx
Labels: codeball:needs-review

#1169 docs: new homepage
  src/components/Footer/footer.scss
  src/locale/en-US.js
  src/locale/zh-CN.js
  src/sitePages/newHome/components/application/application.jsx
  src/sitePages/newHome/components/application/application.module.scss
  src/sitePages/newHome/components/banner/banner.jsx
  src/sitePages/newHome/components/banner/banner.module.scss
  src/sitePages/newHome/components/comments/comments.jsx
  src/sitePages/newHome/components/comments/comments.module.scss
  src/sitePages/newHome/components/deepContent/deepContent.jsx
  src/sitePages/newHome/components/deepContent/deepContent.module.scss
  src/sitePages/newHome/components/dsm/dsm.jsx
  src/sitePages/newHome/components/dsm/dsm.module.scss
  src/sitePages/newHome/components/feature/feature.jsx
  src/sitePages/newHome/components/feature/feature.module.scss
  src/sitePages/newHome/components/operateButton/operateButton.jsx
  src/sitePages/newHome/components/operateButton/operateButton.module.scss
  src/sitePages/newHome/components/pro/d2cApplication/index.jsx
  src/sitePages/newHome/components/pro/d2cApplication/index.module.scss
  src/sitePages/newHome/components/pro/pro.jsx
  src/sitePages/newHome/components/pro/pro.module.scss
  src/sitePages/newHome/components/products/products.jsx
  src/sitePages/newHome/components/products/products.module.scss
  src/sitePages/newHome/components/resource/resource.jsx
  src/sitePages/newHome/components/resource/resource.module.scss
  src/sitePages/newHome/components/svg.jsx
  src/sitePages/newHome/components/theme/components/demo/index.module.scss
  src/sitePages/newHome/components/theme/theme.js
  src/sitePages/newHome/components/theme/theme.jsx
  src/sitePages/newHome/components/theme/theme.module.scss
  src/sitePages/newHome/components/theme/themeConfig.module.scss
  src/sitePages/newHome/index.jsx
  src/sitePages/newHome/index.module.scss
Labels: codeball:needs-careful-review

#1187 fix: fix modal esc trigger close callback after close
  packages/semi-foundation/modal/modalContentFoundation.ts
  packages/semi-ui/modal/ModalContent.tsx
Labels: codeball:approved

#1182 Fix: Change the component that implements the expand/collapse animation in NodeList
  packages/semi-ui/collapsible/index.tsx
  packages/semi-ui/tree/collapse.tsx
  packages/semi-ui/tree/nodeCollapsible.tsx
  packages/semi-ui/tree/nodeList.tsx
  yarn.lock
Labels: codeball:needs-careful-review

#1194 fix: fix select_scss_importOrder for option scss override theme variable
  packages/semi-foundation/select/select.scss
Labels: codeball:approved

#1200 fix: fix cypress faild
  cypress/integration/carousel.spec.js
  cypress/integration/datePicker.spec.js
Labels: codeball:approved

#1197 fix: Table defaultFilterdValue and defaultSortOrder bug #1188
  packages/semi-foundation/table/foundation.ts
  packages/semi-ui/table/Table.tsx
  packages/semi-ui/table/__test__/table.test.js
  packages/semi-ui/table/_story/v2/Fixed1188/index.tsx
  packages/semi-ui/table/_story/v2/index.js
Labels: codeball:needs-careful-review

#1193 Fix foundation event and type
  packages/semi-foundation/autoComplete/foundation.ts
  packages/semi-foundation/base/foundation.ts
  packages/semi-foundation/checkbox/checkboxFoundation.ts
  packages/semi-foundation/form/utils.ts
  packages/semi-foundation/image/previewImageFoundation.ts
  packages/semi-foundation/image/previewInnerFoundation.ts
  packages/semi-foundation/input/textareaFoundation.ts
  packages/semi-foundation/inputNumber/foundation.ts
  packages/semi-foundation/rating/foundation.ts
  packages/semi-foundation/slider/foundation.ts
  packages/semi-foundation/table/foundation.ts
  packages/semi-ui/_base/baseComponent.tsx
  packages/semi-ui/autoComplete/index.tsx
  packages/semi-ui/checkbox/checkbox.tsx
  packages/semi-ui/checkbox/checkboxGroup.tsx
  packages/semi-ui/checkbox/context.ts
  packages/semi-ui/image/previewFooter.tsx
  packages/semi-ui/image/previewImage.tsx
  packages/semi-ui/image/previewInner.tsx
  packages/semi-ui/input/textarea.tsx
  packages/semi-ui/inputNumber/index.tsx
  packages/semi-ui/package.json
  packages/semi-ui/rating/item.tsx
  packages/semi-ui/slider/index.tsx
  packages/semi-ui/table/Table.tsx
Labels: codeball:needs-careful-review

#1203 fix: [Cascader] Fix when motion is false, after searching for the sel…
  packages/semi-foundation/cascader/foundation.ts
Labels: codeball:approved

#1198 feat: disabledDate add rangeInputFocus to second params
  content/input/datepicker/index-en-US.md
  content/input/datepicker/index.md
  cypress/integration/datePicker.spec.js
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-ui/datePicker/_story/v2/DisabledRange.tsx
  packages/semi-ui/datePicker/_story/v2/index.js
  packages/semi-ui/datePicker/month.tsx
Labels: codeball:needs-review

#1211 feat: Optimize the scrolling animation, change the ScrollItem mode in…
  content/input/datepicker/index-en-US.md
  content/input/datepicker/index.md
  content/input/timepicker/index-en-US.md
  content/input/timepicker/index.md
  content/show/scrolllist/index-en-US.md
  content/show/scrolllist/index.md
  packages/semi-foundation/datePicker/datePicker.scss
  packages/semi-foundation/datePicker/yearAndMonthFoundation.ts
  packages/semi-foundation/scrollList/scrollList.scss
  packages/semi-foundation/timePicker/timePicker.scss
  packages/semi-ui/datePicker/datePicker.tsx
  packages/semi-ui/datePicker/monthsGrid.tsx
  packages/semi-ui/datePicker/yearAndMonth.tsx
  packages/semi-ui/scrollList/_story/WheelList/index.jsx
  packages/semi-ui/scrollList/scrollItem.tsx
  packages/semi-ui/timePicker/Combobox.tsx
Labels: codeball:needs-review

#1204 style: [Nav] fix the issue that the padding of NavItem in Dropdown is…
  packages/semi-foundation/navigation/navigation.scss
Labels: codeball:approved

#1213 Fixed the flickering problem when the pop-up window closes after searching in Cascader
  packages/semi-foundation/cascader/foundation.ts
Labels: codeball:approved

#1214 timpicker scrollbar adapt to firefox and ie and update test case
  cypress/integration/timePicker.spec.js
  packages/semi-foundation/datePicker/datePicker.scss
  packages/semi-foundation/timePicker/timePicker.scss
  packages/semi-ui/timePicker/__test__/timePicker.test.js
Labels: codeball:needs-review

#1195 feat: add a11y to navigation
  content/navigation/navigation/index-en-US.md
  content/navigation/navigation/index.md
  packages/semi-foundation/navigation/itemFoundation.ts
  packages/semi-foundation/navigation/navigation.scss
  packages/semi-foundation/navigation/variables.scss
  packages/semi-ui/dropdown/dropdownItem.tsx
  packages/semi-ui/navigation/Item.tsx
  packages/semi-ui/navigation/SubNav.tsx
  packages/semi-ui/navigation/_story/navigation.stories.jsx
Labels: codeball:needs-careful-review

#1212 Feat: [Select] Added showRestTagsPopover and restTagsPopoverProps to support displaying redundant tags through popover
  content/input/select/index-en-US.md
  content/input/select/index.md
  packages/semi-foundation/select/foundation.ts
  packages/semi-ui/select/_story/select.stories.jsx
  packages/semi-ui/select/index.tsx
  packages/semi-ui/tag/group.tsx
  packages/semi-ui/tag/index.tsx
  packages/semi-ui/tag/interface.ts
Labels: codeball:needs-careful-review

#1210 Feat: [TreeSelect] adds showRestTagsPopover and restTagsPopoverProps parameters
  content/input/treeselect/index-en-US.md
  content/input/treeselect/index.md
  packages/semi-foundation/treeSelect/foundation.ts
  packages/semi-ui/cascader/index.tsx
  packages/semi-ui/treeSelect/index.tsx
Labels: codeball:needs-review

#1215 Js2css motion type fix
  packages/semi-foundation/utils/uuid.ts
  packages/semi-ui/autoComplete/index.tsx
  packages/semi-ui/collapse/collapse-context.tsx
  packages/semi-ui/dropdown/index.tsx
  packages/semi-ui/modal/confirm.tsx
  packages/semi-ui/modal/useModal/HookModal.tsx
  packages/semi-ui/navigation/index.tsx
  packages/semi-ui/popconfirm/index.tsx
  packages/semi-ui/popover/index.tsx
  packages/semi-ui/tabs/interface.ts
  packages/semi-ui/timePicker/TimePicker.tsx
  packages/semi-ui/toast/index.tsx
  packages/semi-ui/tooltip/_story/tooltip.stories.jsx
  packages/semi-ui/tooltip/index.tsx
  packages/semi-ui/treeSelect/index.tsx
Labels: codeball:needs-careful-review

#1218 fix: collapsible onMotionEnd exec fallback
  packages/semi-ui/collapsible/index.tsx
Labels: codeball:approved

#1222 fix: datepicker make the same width under wheel and normal mode
  packages/semi-foundation/datePicker/datePicker.scss
  packages/semi-foundation/datePicker/variables.scss
Labels: codeball:needs-review

#1223 fix: fix popover content autoFocus
  packages/semi-foundation/dropdown/dropdown.scss
  packages/semi-foundation/popover/popover.scss
  packages/semi-foundation/tooltip/tooltip.scss
  packages/semi-ui/tooltip/index.tsx
Labels: codeball:approved

#1227 fix: fix tooltip animation in react18 #1225
  packages/semi-ui/_cssAnimation/index.tsx
  packages/semi-ui/tooltip/index.tsx
Labels: codeball:needs-review
