Repository DouyinFE/semi-design, pull requests merged in 2023-05, with the labels that each got.

#1588 fix: Fix the wrong background color of different themes on the homepage
  src/sitePages/newHome/components/theme/theme.js
Labels: codeball:approved

#1586 fix: fixed DatePicker timeZone map logic and use Etc/GMT* id #1585
  packages/semi-foundation/utils/date-fns-extra.ts
  packages/semi-ui/datePicker/_story/v2/FeatEtcGMT.tsx
  packages/semi-ui/datePicker/_story/v2/index.js
Labels: codeball:needs-review

#1590 Fix/breadcrumb max item count
  cypress/integration/breadcrumb.spec.js
  packages/semi-ui/breadcrumb/_story/breadcrumb.stories.jsx
  packages/semi-ui/breadcrumb/index.tsx
Labels: codeball:needs-review

#1593 fix: fix datePicker disabledDate bug #1592
  cypress/integration/datePicker.spec.js
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-ui/datePicker/_story/v2/FixDisabledDate.tsx
  packages/semi-ui/datePicker/_story/v2/index.js
  packages/semi-ui/datePicker/datePicker.tsx
Labels: codeball:needs-review

#1598 Fix search input icon
  packages/semi-foundation/input/input.scss
  packages/semi-ui/input/_story/input.stories.jsx
Labels: codeball:needs-review

#1603 fix: select is single select and renderSelectedItem, the placeholder is not displayed when the value is null #1584
  packages/semi-foundation/select/foundation.ts
  packages/semi-ui/select/_story/select.stories.jsx
Labels: codeball:approved

#1587 fix: fix vertical slider click rail always jump to 1 in some sitiuation
  packages/semi-foundation/slider/foundation.ts
Labels: codeball:needs-review

#1602 feat: add search ref method on select
  content/input/select/index-en-US.md
  content/input/select/index.md
  packages/semi-ui/select/index.tsx
Labels: codeball:needs-careful-review

#1609 style: fixed DatePicker vertical-align bug #1561
  packages/semi-foundation/datePicker/datePicker.scss
Labels: codeball:needs-review

#1614 fix: Table column align bug #1599
  packages/semi-foundation/table/table.scss
  packages/semi-ui/table/_story/v2/FixedColumnAlign/index.tsx
  packages/semi-ui/table/_story/v2/index.js
Labels: codeball:needs-careful-review

#1581 fix: [Typography] remove unnecessary ellipsis waring when ellipsis no…
  packages/semi-ui/typography/_story/typography.stories.jsx
  packages/semi-ui/typography/base.tsx
Labels: codeball:needs-careful-review

#1617 fix: timepicker under timezone and controll get the wrong time after select in panel in 1.3.8 date-fns-tz
  packages/semi-foundation/timePicker/foundation.ts
  packages/semi-ui/timePicker/_story/timepicker.stories.jsx
Labels: codeball:needs-review

#1621 feat: DatePicker support startYear and endYear #1620
  content/input/datepicker/index-en-US.md
  content/input/datepicker/index.md
  packages/semi-foundation/datePicker/_utils/getYears.ts
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-foundation/datePicker/monthsGridFoundation.ts
  packages/semi-foundation/datePicker/yearAndMonthFoundation.ts
  packages/semi-ui/datePicker/_story/v2/FeatYearScrollRange.tsx
  packages/semi-ui/datePicker/_story/v2/index.js
  packages/semi-ui/datePicker/datePicker.tsx
  packages/semi-ui/datePicker/monthsGrid.tsx
  packages/semi-ui/datePicker/yearAndMonth.tsx
Labels: codeball:needs-review

#1589 Chore update storybook & Webpack & Cypress
  .codesandbox/ci.json
  .eslintrc.js
  .github/workflows/cypress.yml
  .storybook/base/base.js
  .storybook/js/main.js
  cypress.config.ts
  cypress.json
  cypress/e2e/anchor.spec.js
  cypress/e2e/autoComplete.spec.js
  cypress/e2e/avatar.spec.js
  cypress/e2e/breadcrumb.spec.js
  cypress/e2e/calendar.spec.js
  cypress/e2e/carousel.spec.js
  cypress/e2e/cascader.spec.js
  cypress/e2e/checkbox.spec.js
  cypress/e2e/datePicker.spec.js
  cypress/e2e/form.spec.js
  cypress/e2e/helloworld.spec.js
  cypress/e2e/image.spec.js
  cypress/e2e/input.spec.js
  cypress/e2e/inputNumber.spec.js
  cypress/e2e/modal.spec.js
  cypress/e2e/navigation.spec.js
  cypress/e2e/notification.spec.js
  cypress/e2e/overflowList.spec.js
  cypress/e2e/popconfirm.spec.js
  cypress/e2e/popover.spec.js
  cypress/e2e/radio.spec.js
  cypress/e2e/rating.spec.js
  cypress/e2e/scrollList.spec.js
  cypress/e2e/select.spec.js
  cypress/e2e/slider.spec.js
  cypress/e2e/table.spec.js
  cypress/e2e/tabs.spec.js
  cypress/e2e/tag.spec.js
  cypress/e2e/tagInput.spec.js
  cypress/e2e/textarea.spec.js
  cypress/e2e/timePicker.spec.js
  cypress/e2e/toast.spec.js
  cypress/e2e/tooltip.spec.js
  cypress/e2e/tree.spec.js
  cypress/e2e/treeSelect.spec.js
  cypress/e2e/typography.spec.js
  cypress/e2e/upload.spec.js
  cypress/integration/overflowList.spec.js
  cypress/support/e2e.js
  cypress/tsconfig.json
  package.json
  packages/semi-ui/anchor/_story/anchor.stories.jsx
  packages/semi-ui/datePicker/_story/datePicker.stories.jsx
  packages/semi-ui/divider/_story/divider.stories.jsx
  packages/semi-ui/dropdown/_story/dropdown.stories.jsx
  packages/semi-ui/form/_story/ArrayField/4-manualSetUsage.jsx
  packages/semi-ui/locale/_story/locale.stories.jsx
  packages/semi-ui/table/_story/RTL/Direction.jsx
  packages/semi-ui/table/_story/table.stories.jsx
  packages/semi-ui/table/_story/v2/index.js
  yarn.lock
Labels: codeball:needs-careful-review

#1619 fix: Table onChange filters is empty when onFilter is not passing #1572
  cypress/e2e/table.spec.js
  packages/semi-foundation/table/foundation.ts
  packages/semi-ui/table/_story/v2/FixOnChange/index.tsx
  packages/semi-ui/table/_story/v2/index.js
Labels: codeball:needs-review

#1631 fix: fix typography header className undefined && chore: add borderle…
  content/input/cascader/index-en-US.md
  content/input/cascader/index.md
  content/input/datepicker/index-en-US.md
  content/input/datepicker/index.md
  content/input/input/index-en-US.md
  content/input/input/index.md
  content/input/select/index-en-US.md
  content/input/select/index.md
  content/input/timepicker/index-en-US.md
  content/input/timepicker/index.md
  content/input/treeselect/index-en-US.md
  content/input/treeselect/index.md
  packages/semi-ui/typography/base.tsx
Labels: codeball:needs-review

#1594 fix: [Image] Put the declaration of the IntersectionObserver object in ImagePreview in componentdidMount to prevent errors in SSR scenarios
  packages/semi-ui/image/image.tsx
  packages/semi-ui/image/preview.tsx
Labels: codeball:needs-review
