Repository DouyinFE/semi-design, pull requests merged in 2023-03, with the labels that each got.

#1465 Feat add material
  content/basic/layout/index-en-US.md
  content/basic/layout/index.md
  content/input/button/index-en-US.md
  content/input/button/index.md
  content/input/checkbox/index-en-US.md
  content/input/checkbox/index.md
  content/input/input/index-en-US.md
  content/input/input/index.md
  content/input/radio/index-en-US.md
  content/input/radio/index.md
  content/input/select/index-en-US.md
  content/input/select/index.md
  content/input/transfer/index.md
  content/navigation/navigation/index-en-US.md
  content/navigation/navigation/index.md
  content/show/card/index-en-US.md
  content/show/card/index.md
  content/show/dropdown/index-en-US.md
  content/show/dropdown/index.md
  content/show/modal/index-en-US.md
  content/show/modal/index.md
  content/show/table/index.md
  content/show/tooltip/index-en-US.md
  content/show/tooltip/index.md
  gatsby-node.js
  src/html.js
  src/templates/postTemplate.js
Labels: codeball:needs-careful-review

#1439 feat: [Typography] Copy nodes in Typograpy support customization
  content/basic/typography/index-en-US.md
  content/basic/typography/index.md
  packages/semi-ui/typography/_story/typography.stories.jsx
  packages/semi-ui/typography/copyable.tsx
  yarn.lock
Labels: codeball:needs-careful-review

#1477 style: [Cascader] fix cursor position incorrent in cascader, single-s…
  packages/semi-foundation/cascader/cascader.scss
  packages/semi-foundation/cascader/variables.scss
  packages/semi-ui/cascader/_story/cascader.stories.jsx
  packages/semi-ui/cascader/index.tsx
Labels: codeball:needs-review

#1475 style: [Tag] children is string type child can be omitted, otherwise …
  packages/semi-foundation/tag/tag.scss
  packages/semi-ui/tag/index.tsx
  packages/semi-ui/tagInput/index.tsx
Labels: codeball:needs-review

#1473 fix: [Cascader] Fix for the single-select, searchable, and Value-cont…
  cypress/integration/cascader.spec.js
  packages/semi-foundation/cascader/foundation.ts
  packages/semi-ui/cascader/_story/cascader.stories.jsx
Labels: codeball:needs-review

#1474 feat: Table fixed column support RTL and fixed align bug in RTL #1471
  .storybook/base/base.js
  content/other/configprovider/index-en-US.md
  content/other/configprovider/index.md
  content/show/table/index-en-US.md
  content/show/table/index.md
  packages/semi-foundation/table/rtl.scss
  packages/semi-foundation/table/table.scss
  packages/semi-foundation/table/utils.ts
  packages/semi-ui/configProvider/_story/RTLDirection/RTLWrapper.tsx
  packages/semi-ui/table/Body/index.tsx
  packages/semi-ui/table/Table.tsx
  packages/semi-ui/table/TableCell.tsx
  packages/semi-ui/table/TableContextProvider.tsx
  packages/semi-ui/table/TableHeaderRow.tsx
  packages/semi-ui/table/_story/RTL/ColumnAlign.tsx
  packages/semi-ui/table/_story/RTL/Direction.jsx
  packages/semi-ui/table/_story/RTL/index.jsx
  packages/semi-ui/table/_story/table.stories.jsx
  packages/semi-ui/table/_story/v2/columnAlign.tsx
  packages/semi-ui/table/index.tsx
  packages/semi-ui/table/interface.ts
  packages/semi-ui/table/table-context.ts
Labels: codeball:needs-careful-review

#1486 fix: [TreeSelect] Fix single selection, filterTreeNode and virtualize…
  cypress/integration/treeSelect.spec.js
  packages/semi-ui/select/virtualRow.tsx
  packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
  packages/semi-ui/treeSelect/index.tsx
Labels: codeball:needs-review

#1485 fix: select onSearch add event param to detech operation origin
  content/input/select/index-en-US.md
  content/input/select/index.md
  packages/semi-foundation/select/foundation.ts
  packages/semi-ui/select/index.tsx
Labels: codeball:needs-careful-review

#1484 fix: Table rowSelection header checkbox status bug #325
  cypress/integration/table.spec.js
  packages/semi-foundation/table/foundation.ts
  packages/semi-ui/table/ColumnSelection.tsx
  packages/semi-ui/table/Table.tsx
  packages/semi-ui/table/_story/Demos/rowSelection.jsx
  packages/semi-ui/table/_story/table.stories.jsx
Labels: codeball:needs-review

#1495 fix: props children update carousel did no rerender and ref.play should have the highest priority
  packages/semi-foundation/carousel/foundation.ts
  packages/semi-ui/carousel/_story/carousel.stories.jsx
  packages/semi-ui/carousel/index.tsx
Labels: codeball:needs-review

#1496 fix: [ImagePreview] Fix the ratio of the new picture is incorrect aft…
  cypress/integration/image.spec.js
  packages/semi-foundation/image/previewImageFoundation.ts
  packages/semi-foundation/image/previewInnerFoundation.ts
  packages/semi-ui/image/previewInner.tsx
Labels: codeball:needs-review

#1470 feat: DatePicker support onClickOutside, open, close methods
  content/input/datepicker/index-en-US.md
  content/input/datepicker/index.md
  cypress/integration/datePicker.spec.js
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-ui/datePicker/_story/v2/FeatOnClickOutside.tsx
  packages/semi-ui/datePicker/_story/v2/FeatRefClass.tsx
  packages/semi-ui/datePicker/_story/v2/FeatRefFocus.tsx
  packages/semi-ui/datePicker/_story/v2/FeatRefOpen.tsx
  packages/semi-ui/datePicker/_story/v2/FixNeedConfirmInTabs.tsx
  packages/semi-ui/datePicker/_story/v2/index.js
  packages/semi-ui/datePicker/dateInput.tsx
  packages/semi-ui/datePicker/datePicker.tsx
  packages/semi-ui/datePicker/index.tsx
  packages/semi-ui/space/index.tsx
Labels: codeball:needs-careful-review

#1511 fix: fix nav tooltip delay
  packages/semi-ui/navigation/Item.tsx
  packages/semi-ui/navigation/nav-context.ts
Labels: codeball:needs-review

#1510 fix: select remote + autoClearSearchValue false update list not show,…
  cypress/integration/select.spec.js
  packages/semi-foundation/select/foundation.ts
  packages/semi-ui/select/_story/select.stories.jsx
Labels: codeball:needs-review

#1509 fix: fixed resizable table with form threw error in dev #1506
  packages/semi-eslint-plugin/__tests__/index.js
  packages/semi-eslint-plugin/src/rules/no-import.ts
  packages/semi-foundation/table/utils.ts
  packages/semi-ui/_utils/index.tsx
  packages/semi-ui/table/ResizableTable.tsx
  packages/semi-ui/table/_story/v2/fixedResizableWithForm.tsx
  packages/semi-ui/table/_story/v2/index.js
  packages/semi-ui/table/utils.ts
Labels: codeball:needs-review

#1512 feat: [TreeSelect] add clicktriggertohide API
  content/input/treeselect/index-en-US.md
  content/input/treeselect/index.md
  cypress/integration/treeSelect.spec.js
  packages/semi-foundation/treeSelect/foundation.ts
  packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
  packages/semi-ui/treeSelect/index.tsx
  yarn.lock
Labels: codeball:needs-review

#1501 fix: [Switch] Change the initial setting of the state in the construc…
  packages/semi-foundation/switch/foundation.ts
  packages/semi-ui/switch/index.tsx
Labels: codeball:needs-review

#1516 feat: [TreeSelect][Cascader] add onSearch & onRemove method for trigg…
  content/input/cascader/index-en-US.md
  content/input/cascader/index.md
  content/input/select/index-en-US.md
  content/input/select/index.md
  content/input/treeselect/index-en-US.md
  content/input/treeselect/index.md
  packages/semi-foundation/cascader/foundation.ts
  packages/semi-foundation/treeSelect/foundation.ts
  packages/semi-ui/cascader/_story/cascader.stories.jsx
  packages/semi-ui/cascader/index.tsx
  packages/semi-ui/select/index.tsx
  packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
  packages/semi-ui/treeSelect/index.tsx
Labels: codeball:needs-review

#1504 feat: add type monthRange to datePicker
  content/input/datepicker/index-en-US.md
  content/input/datepicker/index.md
  cypress/integration/datePicker.spec.js
  packages/semi-foundation/datePicker/_utils/getDefaultFormatToken.ts
  packages/semi-foundation/datePicker/_utils/getInsetInputFormatToken.ts
  packages/semi-foundation/datePicker/_utils/getInsetInputValueFromInsetInputStr.ts
  packages/semi-foundation/datePicker/constants.ts
  packages/semi-foundation/datePicker/datePicker.scss
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-foundation/datePicker/inputFoundation.ts
  packages/semi-foundation/datePicker/variables.scss
  packages/semi-foundation/datePicker/yearAndMonthFoundation.ts
  packages/semi-ui/datePicker/_story/datePicker.stories.jsx
  packages/semi-ui/datePicker/dateInput.tsx
  packages/semi-ui/datePicker/datePicker.tsx
  packages/semi-ui/datePicker/monthsGrid.tsx
  packages/semi-ui/datePicker/yearAndMonth.tsx
  packages/semi-ui/locale/interface.ts
  packages/semi-ui/locale/source/ar.ts
  packages/semi-ui/locale/source/de.ts
  packages/semi-ui/locale/source/en_GB.ts
  packages/semi-ui/locale/source/en_US.ts
  packages/semi-ui/locale/source/es.ts
  packages/semi-ui/locale/source/fr.ts
  packages/semi-ui/locale/source/id_ID.ts
  packages/semi-ui/locale/source/it.ts
  packages/semi-ui/locale/source/ja_JP.ts
  packages/semi-ui/locale/source/ko_KR.ts
  packages/semi-ui/locale/source/ms_MY.ts
  packages/semi-ui/locale/source/nl_NL.ts
  packages/semi-ui/locale/source/pl_PL.ts
  packages/semi-ui/locale/source/pt_BR.ts
  packages/semi-ui/locale/source/ro.ts
  packages/semi-ui/locale/source/ru_RU.ts
  packages/semi-ui/locale/source/sv_SE.ts
  packages/semi-ui/locale/source/th_TH.ts
  packages/semi-ui/locale/source/tr_TR.ts
  packages/semi-ui/locale/source/vi_VN.ts
  packages/semi-ui/locale/source/zh_CN.ts
  packages/semi-ui/locale/source/zh_TW.ts
Labels: feature request, codeball:needs-careful-review

#1521 docs: [TreeSelect] custom trigger example optimization
  content/input/treeselect/index-en-US.md
  content/input/treeselect/index.md
  packages/semi-foundation/treeSelect/foundation.ts
  packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
Labels: codeball:needs-review

#1525 fix: setting zebra pattern is invalid
  packages/semi-foundation/table/table.scss
  packages/semi-foundation/table/variables.scss
  packages/semi-ui/table/_story/v2/index.js
  packages/semi-ui/table/_story/v2/zebra.tsx
Labels: codeball:needs-careful-review

#1519 fix: fixed resizable Table bug #1506
  packages/semi-foundation/table/utils.ts
  packages/semi-ui/table/Table.tsx
Labels: codeball:needs-review

#1529 fix: modal popupContainer exec time
  packages/semi-ui/modal/Modal.tsx
Labels: codeball:approved

#1508 fix: add vertical-align top to fix wrong height
  packages/semi-foundation/autoComplete/autoComplete.scss
  packages/semi-foundation/spin/spin.scss
  packages/semi-foundation/tree/tree.scss
  packages/semi-foundation/upload/upload.scss
Labels: codeball:needs-review
