Repository DouyinFE/semi-design, pull requests merged in 2023-06, with the labels that each got.

#1630 Feat: pass data attribute to dom
  packages/semi-foundation/utils/getDataAttr.ts
  packages/semi-ui/_base/baseComponent.tsx
  packages/semi-ui/anchor/index.tsx
  packages/semi-ui/autoComplete/index.tsx
  packages/semi-ui/banner/index.tsx
  packages/semi-ui/breadcrumb/index.tsx
  packages/semi-ui/breadcrumb/item.tsx
  packages/semi-ui/calendar/dayCalendar.tsx
  packages/semi-ui/calendar/monthCalendar.tsx
  packages/semi-ui/calendar/rangeCalendar.tsx
  packages/semi-ui/calendar/weekCalendar.tsx
  packages/semi-ui/carousel/index.tsx
  packages/semi-ui/cascader/index.tsx
  packages/semi-ui/checkbox/checkbox.tsx
  packages/semi-ui/checkbox/checkboxGroup.tsx
  packages/semi-ui/collapse/index.tsx
  packages/semi-ui/collapsible/index.tsx
  packages/semi-ui/datePicker/datePicker.tsx
  packages/semi-ui/descriptions/index.tsx
  packages/semi-ui/descriptions/item.tsx
  packages/semi-ui/empty/index.tsx
  packages/semi-ui/list/index.tsx
  packages/semi-ui/list/item.tsx
  packages/semi-ui/modal/ModalContent.tsx
  packages/semi-ui/navigation/index.tsx
  packages/semi-ui/pagination/index.tsx
  packages/semi-ui/progress/index.tsx
  packages/semi-ui/radio/radio.tsx
  packages/semi-ui/radio/radioGroup.tsx
  packages/semi-ui/rating/index.tsx
  packages/semi-ui/scrollList/index.tsx
  packages/semi-ui/select/index.tsx
  packages/semi-ui/sideSheet/SideSheetContent.tsx
  packages/semi-ui/slider/index.tsx
  packages/semi-ui/spin/index.tsx
  packages/semi-ui/steps/basicSteps.tsx
  packages/semi-ui/steps/fillSteps.tsx
  packages/semi-ui/steps/navSteps.tsx
  packages/semi-ui/switch/index.tsx
  packages/semi-ui/table/Table.tsx
  packages/semi-ui/tabs/index.tsx
  packages/semi-ui/tagInput/index.tsx
  packages/semi-ui/timeline/index.tsx
  packages/semi-ui/timeline/item.tsx
  packages/semi-ui/transfer/index.tsx
  packages/semi-ui/tree/index.tsx
  packages/semi-ui/treeSelect/index.tsx
  packages/semi-ui/upload/index.tsx
Labels: feature request, codeball:needs-careful-review

#1623 Style/tooltip
  content/basic/typography/index-en-US.md
  content/basic/typography/index.md
  content/show/tooltip/index-en-US.md
  content/show/tooltip/index.md
  content/start/faq/index-en-US.md
  content/start/faq/index.md
  packages/semi-foundation/notification/notification.scss
  packages/semi-foundation/toast/toast.scss
  packages/semi-foundation/tooltip/tooltip.scss
  packages/semi-ui/notification/_story/notification.stories.jsx
  packages/semi-ui/toast/_story/toast.stories.jsx
  packages/semi-ui/tooltip/_story/tooltip.stories.jsx
  packages/semi-ui/tooltip/index.tsx
Labels: codeball:needs-review

#1646 chore: ignore test cases that are runnable locally but have problems …
  cypress/e2e/typography.spec.js
Labels: codeball:needs-review

#1654 chore: udpate ci lerna version
  .github/workflows/cypress.yml
  .github/workflows/lighthouse.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test.yml
  package.json
Labels: codeball:needs-review

#1656 fix: refresh thumb pic when beforeUpload update fileInstance
  content/input/upload/index.md
  packages/semi-foundation/upload/foundation.ts
Labels: codeball:needs-review

#1653 fix: TreeSelect searchAutoFocous preventScroll bug
  packages/semi-ui/input/index.tsx
  packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
  packages/semi-ui/treeSelect/index.tsx
Labels: codeball:needs-careful-review

#1660 fix: [Pagination] fix error x-semi-props for newxText
  packages/semi-ui/pagination/index.tsx
Labels: codeball:approved

#1659 fix: Fix the problem that className does not take effect in ImagePreview
  packages/semi-ui/image/preview.tsx
Labels: codeball:approved

#1670 fix: [Cascader] Fix cascader cannot display +N Popover in disabled an…
  packages/semi-foundation/cascader/cascader.scss
  packages/semi-ui/cascader/_story/cascader.stories.jsx
  packages/semi-ui/cascader/index.tsx
Labels: codeball:needs-review

#1664 chore: correct the problem of the parameter type of Form formApi.reset
  content/feedback/notification/index-en-US.md
  content/feedback/notification/index.md
  content/feedback/popconfirm/index-en-US.md
  content/feedback/popconfirm/index.md
  content/feedback/toast/index-en-US.md
  content/feedback/toast/index.md
  content/input/autocomplete/index-en-US.md
  content/input/autocomplete/index.md
  content/input/cascader/index-en-US.md
  content/input/cascader/index.md
  content/input/datepicker/index-en-US.md
  content/input/datepicker/index.md
  content/input/form/index-en-US.md
  content/input/form/index.md
  content/input/select/index-en-US.md
  content/input/select/index.md
  content/input/timepicker/index-en-US.md
  content/input/timepicker/index.md
  content/input/treeselect/index-en-US.md
  content/input/treeselect/index.md
  content/navigation/navigation/index.md
  content/other/configprovider/index-en-US.md
  content/other/configprovider/index.md
  content/show/dropdown/index-en-US.md
  content/show/dropdown/index.md
  content/show/image/index-en-US.md
  content/show/image/index.md
  content/show/modal/index-en-US.md
  content/show/modal/index.md
  content/show/popover/index-en-US.md
  content/show/popover/index.md
  content/show/sidesheet/index-en-US.md
  content/show/sidesheet/index.md
  content/show/tooltip/index-en-US.md
  content/show/tooltip/index.md
  packages/semi-foundation/form/interface.ts
Labels: codeball:needs-review

#1673 feat: Badge add succss type
  content/show/badge/index-en-US.md
  content/show/badge/index.md
  packages/semi-foundation/badge/badge.scss
  packages/semi-foundation/badge/variables.scss
  packages/semi-ui/badge/_story/badge.stories.jsx
  packages/semi-ui/badge/index.tsx
Labels: codeball:needs-review

#1671 fix: fix toast useToast return value no effect when user function com
  packages/semi-ui/toast/useToast/index.tsx
Labels: codeball:needs-review

#1669 feat: [Tree] Tree add filterExpandedKeys parameter for onSearch
  content/navigation/tree/index-en-US.md
  content/navigation/tree/index.md
  packages/semi-foundation/tree/foundation.ts
  packages/semi-ui/tree/_story/tree.stories.jsx
  packages/semi-ui/tree/index.tsx
Labels: codeball:needs-careful-review

#1651 fix: fixed Cascader disabled tag bg color
  packages/semi-foundation/cascader/cascader.scss
  packages/semi-foundation/cascader/variables.scss
Labels: codeball:needs-review

#1674 refactor: split Toast padding token
  packages/semi-foundation/toast/toast.scss
  packages/semi-foundation/toast/variables.scss
Labels: codeball:needs-review
