Repository DouyinFE/semi-design, pull requests merged in 2023-04, with the labels that each got.

#1536 fix: tabpane use classnames
  packages/semi-ui/tabs/TabPane.tsx
Labels: codeball:approved

#1540 fix: avoid ele.type.name changed after compiler, use static property …
  packages/semi-ui/iconButton/index.tsx
  packages/semi-ui/navigation/Footer.tsx
  packages/semi-ui/navigation/Header.tsx
  packages/semi-ui/navigation/index.tsx
  packages/semi-ui/table/Column.tsx
  packages/semi-ui/table/getColumns.tsx
  packages/semi-ui/tooltip/index.tsx
Labels: codeball:approved

#1538 fix: [Table] Modify the wrong type definition of the filteredValue pa…
  content/show/table/index-en-US.md
  content/show/table/index.md
Labels: codeball:needs-review

#1520 style: [Popconfirm] style optimize for close button in Popconfirm
  cypress/integration/popconfirm.spec.js
  packages/semi-foundation/popconfirm/popconfirm.scss
  packages/semi-foundation/popconfirm/rtl.scss
  packages/semi-foundation/popconfirm/variables.scss
Labels: codeball:needs-review

#1533 style: change typography copy icon from vertical-align text-bottom to middle
  packages/semi-foundation/typography/typography.scss
Labels: codeball:needs-review

#1535 fix: fixed disabledDate rangeStart and rangeEnd cached bug #777
  cypress/integration/datePicker.spec.js
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-ui/datePicker/__test__/datePicker.test.js
  packages/semi-ui/datePicker/_story/v2/dynamicDisabledDate.tsx
  packages/semi-ui/datePicker/_story/v2/index.js
Labels: codeball:needs-review

#1550 fix: fix sidesheet mask=false mask width not correct
  packages/semi-foundation/sideSheet/sideSheet.scss
Labels: codeball:approved

#1544 Fix prefixCls not work when using common js lib
  packages/semi-webpack/package.json
  packages/semi-webpack/src/semi-source-suffix-loader.ts
Labels: codeball:needs-careful-review

#1547 fix: [Tranfer] Fix items with the same label cannot be dragged when t…
  packages/semi-ui/transfer/index.tsx
Labels: codeball:needs-review

#1552 fix: fix ComponentPropsWithRef type function failed with Button
  packages/semi-ui/button/index.tsx
Labels: codeball:approved

#1564 fix: Table indent bug when hideExpandedColumn is false #1556
  package.json
  packages/semi-ui/table/Body/BaseRow.tsx
  packages/semi-ui/table/_story/v2/Fixed1556/index.tsx
  packages/semi-ui/table/_story/v2/index.js
  yarn.lock
Labels: codeball:needs-review

#1559 fix: add stopPropagation to focus and blur event in tooltip portal
  packages/semi-ui/_utils/index.tsx
  packages/semi-ui/tooltip/_story/tooltip.stories.jsx
  packages/semi-ui/tooltip/index.tsx
Labels: bug, codeball:needs-review

#1570 style: Fix the style error when icon and text exist at the same time …
  packages/semi-foundation/breadcrumb/breadcrumb.scss
Labels: codeball:needs-review

#1574 fix: radioGroup add vertical-align, close #1573
  packages/semi-foundation/radio/radio.scss
Labels: codeball:needs-careful-review

#1578 Fix/typo: fix Typography truncation error when setting white-space to nowrap
  packages/semi-ui/typography/_story/typography.stories.jsx
  packages/semi-ui/typography/util.tsx
Labels: codeball:needs-careful-review

#1576 fix: fixed Table SSR dataSource is empty bug #1466
  packages/semi-ui/table/Table.tsx
Labels: codeball:needs-careful-review

#1579 fix: [Image] Fix the image is not loaded normally when the src in Ima…
  cypress/integration/image.spec.js
  packages/semi-ui/image/_story/image.stories.jsx
  packages/semi-ui/image/image.tsx
  packages/semi-ui/image/preview.tsx
  packages/semi-ui/image/previewContext.tsx
Labels: codeball:needs-review
