Repository DouyinFE/semi-design, pull requests merged in 2023-02, with the labels that each got.

#1407 Form.InputGroup support extraText, extraTextPosition
  content/input/form/index-en-US.md
  content/input/form/index.md
  packages/semi-foundation/form/form.scss
  packages/semi-ui/form/_story/InputGroup/groupProps.jsx
  packages/semi-ui/form/_story/Layout/layoutDemo.jsx
  packages/semi-ui/form/_story/form.stories.jsx
  packages/semi-ui/form/group.tsx
Labels: codeball:needs-review

#1406 fix: [DatePicker] fixed input date not show panel bug #1398
  packages/semi-foundation/datePicker/monthsGridFoundation.ts
Labels: codeball:approved

#1405 feat: [DatePicker] insetInput support object type #1343
  content/input/datepicker/index-en-US.md
  content/input/datepicker/index.md
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-foundation/datePicker/inputFoundation.ts
  packages/semi-foundation/datePicker/monthsGridFoundation.ts
  packages/semi-ui/datePicker/_story/v2/FeatInsetInputProps.tsx
  packages/semi-ui/datePicker/_story/v2/index.js
  packages/semi-ui/datePicker/dateInput.tsx
  packages/semi-ui/datePicker/datePicker.tsx
  packages/semi-ui/datePicker/index.tsx
  packages/semi-ui/datePicker/quickControl.tsx
Labels: codeball:needs-careful-review

#1391 feat: (slider) add some tokens
  packages/semi-foundation/slider/slider.scss
  packages/semi-foundation/slider/variables.scss
  packages/semi-ui/slider/index.tsx
Labels: codeball:approved

#1408 feat: [Transfer] Transfer adds renderSourceHeader and renderSelectedH…
  content/input/transfer/index-en-US.md
  content/input/transfer/index.md
  packages/semi-ui/transfer/_story/transfer.stories.jsx
  packages/semi-ui/transfer/index.tsx
Labels: codeball:needs-review

#1411 feat: add i18n locale source, #1410
  content/other/locale/index-en-US.md
  content/other/locale/index.md
  packages/semi-ui/locale/_story/locale.stories.jsx
  packages/semi-ui/locale/interface.ts
  packages/semi-ui/locale/source/ar.ts
  packages/semi-ui/locale/source/de.ts
  packages/semi-ui/locale/source/en_GB.ts
  packages/semi-ui/locale/source/en_US.ts
  packages/semi-ui/locale/source/es.ts
  packages/semi-ui/locale/source/fr.ts
  packages/semi-ui/locale/source/id_ID.ts
  packages/semi-ui/locale/source/it.ts
  packages/semi-ui/locale/source/ja_JP.ts
  packages/semi-ui/locale/source/ko_KR.ts
  packages/semi-ui/locale/source/ms_MY.ts
  packages/semi-ui/locale/source/nl_NL.ts
  packages/semi-ui/locale/source/pl_PL.ts
  packages/semi-ui/locale/source/pt_BR.ts
  packages/semi-ui/locale/source/ro.ts
  packages/semi-ui/locale/source/ru_RU.ts
  packages/semi-ui/locale/source/sv_SE.ts
  packages/semi-ui/locale/source/th_TH.ts
  packages/semi-ui/locale/source/tr_TR.ts
  packages/semi-ui/locale/source/vi_VN.ts
  packages/semi-ui/locale/source/zh_CN.ts
  packages/semi-ui/locale/source/zh_TW.ts
  packages/semi-ui/pagination/index.tsx
  src/templates/scope.js
Labels: codeball:needs-careful-review

#1418 fix: change table bg color to fit dark mode
  packages/semi-foundation/table/table.scss
  packages/semi-foundation/table/variables.scss
Labels: codeball:needs-review

#1414 fix: [DatePicker] insetInput show date bug in controlled mode #1413
  cypress/integration/datePicker.spec.js
  packages/semi-foundation/datePicker/foundation.ts
  packages/semi-ui/datePicker/_story/v2/InsetInputControlled.tsx
  packages/semi-ui/datePicker/_story/v2/index.js
  packages/semi-ui/datePicker/dateInput.tsx
  packages/semi-ui/datePicker/datePicker.tsx
Labels: codeball:needs-review

#1423 fix: [DatePicker] multiple selected panel ui shift #1422
  cypress/integration/datePicker.spec.js
  packages/semi-foundation/datePicker/monthsGridFoundation.ts
  packages/semi-ui/datePicker/_story/v2/FixMultiplePanelShift.tsx
  packages/semi-ui/datePicker/_story/v2/index.js
Labels: codeball:needs-review

#1436 feat: [Cascader] cascader supports calling the open/close method thro…
  content/input/cascader/index-en-US.md
  content/input/cascader/index.md
  packages/semi-ui/cascader/__test__/cascader.test.js
  packages/semi-ui/cascader/_story/cascader.stories.jsx
  packages/semi-ui/cascader/index.tsx
Labels: codeball:needs-review

#1440 fix: add solid tag hover and active color
  packages/semi-foundation/tag/tag.scss
Labels: 💄 Design, codeball:needs-review

#1425 feat(a11y): Popconfirm support focus and keyboard
  content/feedback/popconfirm/index-en-US.md
  content/feedback/popconfirm/index.md
  cypress/integration/popconfirm.spec.js
  packages/semi-foundation/popconfirm/popconfirmFoundation.ts
  packages/semi-foundation/tooltip/foundation.ts
  packages/semi-ui/popconfirm/_story/popconfirm.stories.jsx
  packages/semi-ui/popconfirm/index.tsx
  packages/semi-ui/popover/index.tsx
  packages/semi-ui/tooltip/index.tsx
Labels: codeball:needs-review

#1431 fix: [Numeral] Modify the calculation rules when the rule in the Nume…
  content/basic/typography/index-en-US.md
  content/basic/typography/index.md
  packages/semi-foundation/typography/formatNumeral.ts
Labels: codeball:needs-review

#1446 fix: fix treeselect hover border && select add bg-focus token
  packages/semi-foundation/select/select.scss
  packages/semi-foundation/select/variables.scss
  packages/semi-foundation/treeSelect/treeSelect.scss
  packages/semi-foundation/treeSelect/variables.scss
Labels: codeball:approved

#1447 Docs/homesite
  content/basic/typography/index-en-US.md
  content/basic/typography/index.md
  src/sitePages/newHome/components/comments/comments.jsx
  src/sitePages/newHome/components/operateButton/operateButton.jsx
  src/sitePages/newHome/components/theme/theme.js
Labels: codeball:needs-careful-review

#1450 fix: When the tooltip is blocked on the right side, the floating layer floats to the left side of the viewport
  packages/semi-foundation/tooltip/foundation.ts
  packages/semi-ui/tooltip/_story/tooltip.stories.jsx
Labels: bug, codeball:needs-review

#1444 Fix/onblur: fix the wrong timing of onBlur/onFocus calls in TreeSelect
  cypress/integration/treeSelect.spec.js
  packages/semi-foundation/treeSelect/foundation.ts
  packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
  packages/semi-ui/treeSelect/index.tsx
Labels: codeball:needs-careful-review

#1458 fix(dropdown): fixed Dropdown showTick bug #1457
  packages/semi-ui/dropdown/_story/dropdown.stories.jsx
  packages/semi-ui/dropdown/dropdownItem.tsx
Labels: codeball:needs-review

#1459 fix: modal danger type button color
  packages/semi-ui/modal/confirm.tsx
Labels: codeball:needs-review

#1461 fix: tabindex is transparently passed to tag in any case
  packages/semi-ui/tag/index.tsx
Labels: codeball:needs-review
