Repository DouyinFE/semi-design, pull requests merged in 2023-01, with the labels that each got.

#1358 fix: [Tabs] fix TabBar does not match string warning in SSR
  packages/semi-ui/tabs/TabBar.tsx
Labels: codeball:approved

#1352 docs: fix docs error
  content/input/cascader/index-en-US.md
  content/input/cascader/index.md
Labels: codeball:approved

#1360 feat: add some token
  content/start/changelog/index-en-US.md
  content/start/changelog/index.md
  packages/semi-foundation/datePicker/datePicker.scss
  packages/semi-foundation/datePicker/variables.scss
  packages/semi-foundation/form/form.scss
  packages/semi-foundation/form/variables.scss
  packages/semi-foundation/steps/variables.scss
Labels: codeball:needs-review

#1364 fix: collapse tabs click inner portal sometimes did not work
  packages/semi-ui/tabs/TabBar.tsx
  packages/semi-ui/tooltip/index.tsx
Labels: codeball:needs-careful-review

#1370 fix: [select] remove option focus style when hover slot
  packages/semi-foundation/select/foundation.ts
  packages/semi-ui/select/index.tsx
Labels: codeball:needs-review

#1371 feat: toast new token
  packages/semi-foundation/toast/toast.scss
  packages/semi-foundation/toast/variables.scss
Labels: codeball:needs-review

#1372 other: Dropdown item 新增 showTick 和 hover 属性
  packages/semi-foundation/dropdown/dropdown.scss
  packages/semi-ui/dropdown/_story/C2D/index.tsx
  packages/semi-ui/dropdown/_story/dropdown.stories.jsx
  packages/semi-ui/dropdown/dropdownItem.tsx
Labels: codeball:needs-review

#1373 feat: modal declarative promise
  content/show/modal/index.md
  packages/semi-foundation/base/foundation.ts
  packages/semi-foundation/modal/modalFoundation.ts
  packages/semi-ui/modal/Modal.tsx
Labels: codeball:needs-careful-review

#1379 Fix race async validator when using field props.validate
  packages/semi-ui/form/_story/Validate/validateDemo.jsx
  packages/semi-ui/form/_story/form.stories.jsx
  packages/semi-ui/form/hoc/withField.tsx
  src/sitePages/newHome/components/operateButton/operateButton.jsx
  src/templates/postTemplate.js
Labels: codeball:needs-careful-review

#1382 [Plugin] feat: add overrideLoaderList to webpack plugin
  packages/semi-webpack/README.md
  packages/semi-webpack/src/semi-webpack-plugin.ts
Labels: codeball:needs-review

#1383 feat: [Cascader] Newly added filterSorter, filterRender API, filterTr…
  content/input/cascader/index-en-US.md
  content/input/cascader/index.md
  content/input/treeselect/index-en-US.md
  content/input/treeselect/index.md
  content/navigation/tree/index-en-US.md
  content/navigation/tree/index.md
  package.json
  packages/semi-foundation/cascader/foundation.ts
  packages/semi-foundation/tree/foundation.ts
  packages/semi-foundation/tree/treeUtil.ts
  packages/semi-ui/_base/baseComponent.tsx
  packages/semi-ui/cascader/_story/cascader.stories.jsx
  packages/semi-ui/cascader/index.tsx
  packages/semi-ui/cascader/item.tsx
  packages/semi-ui/scrollList/scrollItem.tsx
  packages/semi-ui/tree/interface.ts
  yarn.lock
Labels: codeball:needs-careful-review

#1385 fix: change_upload_demoURL
  content/input/upload/index-en-US.md
  content/input/upload/index.md
  src/sitePages/newHome/components/operateButton/operateButton.jsx
Labels: codeball:approved

#1374 Feat/tab item
  packages/semi-foundation/tabs/tabs.scss
  packages/semi-ui/overflowList/intersectionObserver.tsx
  packages/semi-ui/tabs/TabBar.tsx
  packages/semi-ui/tabs/TabItem.tsx
  packages/semi-ui/tabs/_story/tabs.stories.jsx
  packages/semi-ui/tabs/index.tsx
Labels: codeball:needs-careful-review

#1384 [layout] Fix layout mount sider class delay
  packages/semi-foundation/base/foundation.ts
  packages/semi-ui/layout/Sider.tsx
  packages/semi-ui/layout/index.tsx
Labels: codeball:needs-careful-review

#1388 fix: select controled mode autoClearSearchValue false not work, #1386
  packages/semi-foundation/select/foundation.ts
  packages/semi-ui/select/_story/select.stories.jsx
Labels: codeball:needs-review

#1353 fix: [Select] modify the tags of trigger display when maxTagCount is exists
  content/input/select/index-en-US.md
  content/input/select/index.md
  packages/semi-foundation/select/foundation.ts
  packages/semi-foundation/select/select.scss
  packages/semi-ui/overflowList/_story/overflowList.stories.jsx
  packages/semi-ui/overflowList/index.tsx
  packages/semi-ui/select/_story/select.stories.jsx
  packages/semi-ui/select/index.tsx
Labels: codeball:needs-careful-review

#1363 fix: OverflowList change items props and scroll vertically to be cover bring the wrong overflow item
  packages/semi-ui/overflowList/_story/overflowList.stories.jsx
  packages/semi-ui/overflowList/index.tsx
Labels: codeball:needs-review

#1392 chore: improve taginput doc
  content/input/taginput/index-en-US.md
  content/input/taginput/index.md
  packages/semi-ui/tagInput/index.tsx
Labels: codeball:needs-review

#1399 fix: under react18 and strictmode new overflowList do not visibility
  packages/semi-ui/resizeObserver/index.tsx
Labels: codeball:approved

#1398 fix: [DatePicker] range type ui shift bug #1221
  cypress/integration/datePicker.spec.js
  packages/semi-foundation/datePicker/monthsGridFoundation.ts
  packages/semi-ui/datePicker/_story/v2/FixRangePanelShift.jsx
  packages/semi-ui/datePicker/_story/v2/index.js
  packages/semi-ui/datePicker/monthsGrid.tsx
Labels: codeball:needs-review

#1400 fix: The non-last child select under the input group has an unexpected scroll bar
  packages/semi-foundation/input/input.scss
Labels: codeball:needs-review
